### PR TITLE
Improve explanation of advanced scripts workflow

### PR DESCRIPTION
**Pull request by pwalczysko**
Add example of output after starting processor for advanced (non-admin) scripting workflow.
See https://www.openmicroscopy.org/site/support/omero5.2-staging/developers/scripts/advanced.html for buit version.

The motivation is also described in [trello card](https://trello.com/c/81ISVYsi/118-cannot-import-script-via-cli#comment-57b59d9982efadf70e294798).

cc @jburel @will-moore

### CODE REVIEW

**Comment by jburel** [comment]
why against 5.2? it seems a rather late change

The doc has been tagged as part of the release. This should go against 5.3

**Comment by hflynn** [comment]
@pwalczysko apologies, I should probably have said to open this against develop at this stage. Shall I just rebase it for you with snoopy or would you prefer to handle it yourself?

**Comment by pwalczysko** [comment]
--rebased-to #1550

**Comment by jburel** [comment]
Closing this PR since we are not planning (yet) another 5.2 release.

**Comment by hflynn** [comment]
Re-opening since another 5.2 release is likely to fix Ice

**Comment by hflynn** [comment]
Replaced with #1564 instead as there were extra commits on develop. Closing again.

**Pull request closed without merging**
