### PR TITLE
Put the auto-generation script under version control (rebased onto dev_5_0)

### PR DESCRIPTION
**Pull request by sbesson**
This is the same as gh-1083 but rebased onto dev_5_0.

----

This PR puts the script that is used by the auto-generation jobs (http://ci.openmicroscopy.org/job/OMERO-5.1-merge-docs-autogen/ and http://ci.openmicroscopy.org/job/OMERO-5.1-latest-docs-autogen/) under version control to simplify its improvements by Pull Requests. 

An extra feature of this PR is to do the substitution of the CI WORKSPACE by `/home/omero` across the board (i.e. including in the configuration properties page).

### CODE REVIEW

**Comment by sbesson** [comment]
--rebased-from #1083

**Comment by sbesson** [comment]
Note last commit should remove the unecessary`develop` specific part of this script.

**Comment by sbesson** [comment]
See https://github.com/snoopycrimecop/ome-documentation/commit/77a2d2234a71938e48cc4849d34eef86523986b6

**Comment by rleigh-dundee** [comment]
This looks fine, though I can't test it.  Looks good to merge.

**Pull request merged**
