### PR TITLE
Extend testing page to cover new ITest features

### PR DESCRIPTION
**Pull request by sbesson**
This PR documents the latest integration tests improvements added in https://github.com/openmicroscopy/openmicroscopy/pull/3618

--no-rebase

### CODE REVIEW

**Comment by ximenesuk** [comment]
Looks good other than the minor comment above.

**Comment by sbesson** [comment]
Pushed.

**Comment by hflynn** [comment]
You happy for me to merge this now @ximenesuk ?

**Comment by ximenesuk** [comment]
Fine by me!

**Comment by hflynn** [comment]
@ximenesuk has confirmed he's happy now, so merging.

**Pull request merged**
