### PR TITLE
linkcheck_ignore ngff.openmicroscopy.org

### PR DESCRIPTION
**Pull request by will-moore**

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#139](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/139/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/139/consoleText) for more details.
Possible conflicts:
  - PR #2298 pwalczysko 'test'
    - omero/conf.py
  - PR #2319 jburel 'exclude ci links from check'
    - omero/conf.py

~~--conflicts~~ Conflict resolved in build [OMERO-docs#140](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/140/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/140/consoleText) for more details.

**Comment by snoopycrimecop** [comment]
Empty PR description. Please add a short summary of the PR scope and some testing instructions.

**Comment by snoopycrimecop** [comment]
Empty PR description. Please add a short summary of the PR scope and some testing instructions.

**Comment by snoopycrimecop** [comment]
Empty PR description. Please add a short summary of the PR scope and some testing instructions.

**Comment by jburel** [comment]
This PR is probably no longer needed since the internal DNS has been updated

**Pull request closed without merging**
