### PR TITLE
Changes from upstream repositories:  openmicroscopy

### PR DESCRIPTION
**Pull request by snoopycrimecop**
- This PR contains changes from upstream repositories

Auto-generated by [create-pull-request][1]

[1]: https://github.com/peter-evans/create-pull-request

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#209](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/209/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/209/consoleText) for more details.
Possible conflicts:
  - PR #2323 dominikl 'Add install docs for ubuntu 22.04'
    - omero/sysadmins/unix/walkthrough/walkthrough_ubuntu2204.sh

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#210](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/210/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/210/consoleText) for more details.
Possible conflicts:
  - PR #2323 dominikl 'Add install docs for ubuntu 22.04'
    - omero/sysadmins/unix/walkthrough/walkthrough_ubuntu2204.sh

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#211](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/211/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/211/consoleText) for more details.
Possible conflicts:
  - PR #2323 dominikl 'Add install docs for ubuntu 22.04'
    - omero/sysadmins/unix/walkthrough/walkthrough_ubuntu2204.sh

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#212](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/212/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/212/consoleText) for more details.
Possible conflicts:
  - PR #2323 dominikl 'Add install docs for ubuntu 22.04'
    - omero/sysadmins/unix/walkthrough/walkthrough_ubuntu2204.sh

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#213](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/213/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/213/consoleText) for more details.
Possible conflicts:
  - PR #2323 dominikl 'Add install docs for ubuntu 22.04'
    - omero/sysadmins/unix/walkthrough/walkthrough_ubuntu2204.sh

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#214](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/214/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/214/consoleText) for more details.
Possible conflicts:
  - PR #2323 dominikl 'Add install docs for ubuntu 22.04'
    - omero/sysadmins/unix/walkthrough/walkthrough_ubuntu2204.sh

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#215](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/215/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/215/consoleText) for more details.
Possible conflicts:
  - PR #2323 dominikl 'Add install docs for ubuntu 22.04'
    - omero/sysadmins/unix/walkthrough/walkthrough_ubuntu2204.sh

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#216](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/216/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/216/consoleText) for more details.
Possible conflicts:
  - PR #2323 dominikl 'Add install docs for ubuntu 22.04'
    - omero/sysadmins/unix/walkthrough/walkthrough_ubuntu2204.sh

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#218](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/218/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/218/consoleText) for more details.
Possible conflicts:
  - PR #2323 dominikl 'Add install docs for ubuntu 22.04'
    - omero/sysadmins/unix/walkthrough/walkthrough_ubuntu2204.sh

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#220](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/220/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/220/consoleText) for more details.
Possible conflicts:
  - PR #2323 dominikl 'Add install docs for ubuntu 22.04'
    - omero/sysadmins/unix/walkthrough/walkthrough_ubuntu2204.sh

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#221](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/221/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/221/consoleText) for more details.
Possible conflicts:
  - PR #2323 dominikl 'Add install docs for ubuntu 22.04'
    - omero/sysadmins/unix/walkthrough/walkthrough_ubuntu2204.sh

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#222](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/222/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/222/consoleText) for more details.
Possible conflicts:
  - PR #2323 dominikl 'Add install docs for ubuntu 22.04'
    - omero/sysadmins/unix/walkthrough/walkthrough_ubuntu2204.sh

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#223](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/223/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/223/consoleText) for more details.
Possible conflicts:
  - PR #2323 dominikl 'Add install docs for ubuntu 22.04'
    - omero/sysadmins/unix/walkthrough/walkthrough_ubuntu2204.sh

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#224](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/224/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/224/consoleText) for more details.
Possible conflicts:
  - PR #2323 dominikl 'Add install docs for ubuntu 22.04'
    - omero/sysadmins/unix/walkthrough/walkthrough_ubuntu2204.sh

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#225](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/225/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/225/consoleText) for more details.
Possible conflicts:
  - PR #2323 dominikl 'Add install docs for ubuntu 22.04'
    - omero/sysadmins/unix/walkthrough/walkthrough_ubuntu2204.sh

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#226](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/226/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/226/consoleText) for more details.
Possible conflicts:
  - PR #2323 dominikl 'Add install docs for ubuntu 22.04'
    - omero/sysadmins/unix/walkthrough/walkthrough_ubuntu2204.sh

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#2](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/2/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/2/consoleText) for more details.
Possible conflicts:
  - PR #2323 dominikl 'Add install docs for ubuntu 22.04'
    - omero/sysadmins/unix/walkthrough/walkthrough_ubuntu2204.sh

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#227](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/227/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/227/consoleText) for more details.
Possible conflicts:
  - PR #2323 dominikl 'Add install docs for ubuntu 22.04'
    - omero/sysadmins/unix/walkthrough/walkthrough_ubuntu2204.sh

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#228](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/228/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/228/consoleText) for more details.
Possible conflicts:
  - PR #2323 dominikl 'Add install docs for ubuntu 22.04'
    - omero/sysadmins/unix/walkthrough/walkthrough_ubuntu2204.sh

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#229](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/229/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/229/consoleText) for more details.
Possible conflicts:
  - PR #2323 dominikl 'Add install docs for ubuntu 22.04'
    - omero/sysadmins/unix/walkthrough/walkthrough_ubuntu2204.sh

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#4](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/4/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/4/consoleText) for more details.
Possible conflicts:
  - PR #2323 dominikl 'Add install docs for ubuntu 22.04'
    - omero/sysadmins/unix/walkthrough/walkthrough_ubuntu2204.sh

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#5](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/5/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/5/consoleText) for more details.
Possible conflicts:
  - PR #2323 dominikl 'Add install docs for ubuntu 22.04'
    - omero/sysadmins/unix/walkthrough/walkthrough_ubuntu2204.sh

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#231](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/231/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/231/consoleText) for more details.
Possible conflicts:
  - PR #2323 dominikl 'Add install docs for ubuntu 22.04'
    - omero/sysadmins/unix/walkthrough/walkthrough_ubuntu2204.sh

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#6](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/6/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/6/consoleText) for more details.
Possible conflicts:
  - PR #2323 dominikl 'Add install docs for ubuntu 22.04'
    - omero/sysadmins/unix/walkthrough/walkthrough_ubuntu2204.sh

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#235](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/235/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/235/consoleText) for more details.
Possible conflicts:
  - PR #2323 dominikl 'Add install docs for ubuntu 22.04'
    - omero/sysadmins/unix/walkthrough/walkthrough_ubuntu2204.sh

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#236](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/236/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/236/consoleText) for more details.
Possible conflicts:
  - PR #2323 dominikl 'Add install docs for ubuntu 22.04'
    - omero/sysadmins/unix/walkthrough/walkthrough_ubuntu2204.sh

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#237](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/237/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/237/consoleText) for more details.
Possible conflicts:
  - PR #2323 dominikl 'Add install docs for ubuntu 22.04'
    - omero/sysadmins/unix/walkthrough/walkthrough_ubuntu2204.sh

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#238](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/238/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/238/consoleText) for more details.
Possible conflicts:
  - PR #2323 dominikl 'Add install docs for ubuntu 22.04'
    - omero/sysadmins/unix/walkthrough/walkthrough_ubuntu2204.sh

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#239](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/239/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/239/consoleText) for more details.
Possible conflicts:
  - PR #2323 dominikl 'Add install docs for ubuntu 22.04'
    - omero/sysadmins/unix/walkthrough/walkthrough_ubuntu2204.sh

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#240](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/240/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/240/consoleText) for more details.
Possible conflicts:
  - PR #2323 dominikl 'Add install docs for ubuntu 22.04'
    - omero/sysadmins/unix/walkthrough/walkthrough_ubuntu2204.sh

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#241](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/241/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/241/consoleText) for more details.
Possible conflicts:
  - PR #2323 dominikl 'Add install docs for ubuntu 22.04'
    - omero/sysadmins/unix/walkthrough/walkthrough_ubuntu2204.sh

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#242](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/242/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/242/consoleText) for more details.
Possible conflicts:
  - PR #2323 dominikl 'Add install docs for ubuntu 22.04'
    - omero/sysadmins/unix/walkthrough/walkthrough_ubuntu2204.sh

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#243](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/243/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/243/consoleText) for more details.
Possible conflicts:
  - PR #2323 dominikl 'Add install docs for ubuntu 22.04'
    - omero/sysadmins/unix/walkthrough/walkthrough_ubuntu2204.sh

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#244](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/244/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/244/consoleText) for more details.
Possible conflicts:
  - PR #2323 dominikl 'Add install docs for ubuntu 22.04'
    - omero/sysadmins/unix/walkthrough/walkthrough_ubuntu2204.sh

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#245](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/245/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/245/consoleText) for more details.
Possible conflicts:
  - PR #2323 dominikl 'Add install docs for ubuntu 22.04'
    - omero/sysadmins/unix/walkthrough/walkthrough_ubuntu2204.sh

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#246](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/246/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/246/consoleText) for more details.
Possible conflicts:
  - PR #2323 dominikl 'Add install docs for ubuntu 22.04'
    - omero/sysadmins/unix/walkthrough/walkthrough_ubuntu2204.sh

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#247](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/247/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/247/consoleText) for more details.
Possible conflicts:
  - PR #2323 dominikl 'Add install docs for ubuntu 22.04'
    - omero/sysadmins/unix/walkthrough/walkthrough_ubuntu2204.sh

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#248](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/248/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/248/consoleText) for more details.
Possible conflicts:
  - PR #2323 dominikl 'Add install docs for ubuntu 22.04'
    - omero/sysadmins/unix/walkthrough/walkthrough_ubuntu2204.sh

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#249](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/249/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/249/consoleText) for more details.
Possible conflicts:
  - PR #2323 dominikl 'Add install docs for ubuntu 22.04'
    - omero/sysadmins/unix/walkthrough/walkthrough_ubuntu2204.sh

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#250](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/250/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/250/consoleText) for more details.
Possible conflicts:
  - PR #2323 dominikl 'Add install docs for ubuntu 22.04'
    - omero/sysadmins/unix/walkthrough/walkthrough_ubuntu2204.sh

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#251](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/251/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/251/consoleText) for more details.
Possible conflicts:
  - PR #2323 dominikl 'Add install docs for ubuntu 22.04'
    - omero/sysadmins/unix/walkthrough/walkthrough_ubuntu2204.sh

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#252](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/252/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/252/consoleText) for more details.
Possible conflicts:
  - PR #2323 dominikl 'Add install docs for ubuntu 22.04'
    - omero/sysadmins/unix/walkthrough/walkthrough_ubuntu2204.sh

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#253](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/253/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/253/consoleText) for more details.
Possible conflicts:
  - PR #2323 dominikl 'Add install docs for ubuntu 22.04'
    - omero/sysadmins/unix/walkthrough/walkthrough_ubuntu2204.sh

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#254](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/254/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/254/consoleText) for more details.
Possible conflicts:
  - PR #2323 dominikl 'Add install docs for ubuntu 22.04'
    - omero/sysadmins/unix/walkthrough/walkthrough_ubuntu2204.sh

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#255](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/255/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/255/consoleText) for more details.
Possible conflicts:
  - PR #2323 dominikl 'Add install docs for ubuntu 22.04'
    - omero/sysadmins/unix/walkthrough/walkthrough_ubuntu2204.sh

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#256](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/256/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/256/consoleText) for more details.
Possible conflicts:
  - PR #2323 dominikl 'Add install docs for ubuntu 22.04'
    - omero/sysadmins/unix/walkthrough/walkthrough_ubuntu2204.sh

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#257](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/257/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/257/consoleText) for more details.
Possible conflicts:
  - PR #2323 dominikl 'Add install docs for ubuntu 22.04'
    - omero/sysadmins/unix/walkthrough/walkthrough_ubuntu2204.sh

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#258](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/258/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/258/consoleText) for more details.
Possible conflicts:
  - PR #2323 dominikl 'Add install docs for ubuntu 22.04'
    - omero/sysadmins/unix/walkthrough/walkthrough_ubuntu2204.sh

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#259](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/259/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/259/consoleText) for more details.
Possible conflicts:
  - PR #2323 dominikl 'Add install docs for ubuntu 22.04'
    - omero/sysadmins/unix/walkthrough/walkthrough_ubuntu2204.sh

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#260](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/260/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/260/consoleText) for more details.
Possible conflicts:
  - PR #2323 dominikl 'Add install docs for ubuntu 22.04'
    - omero/sysadmins/unix/walkthrough/walkthrough_ubuntu2204.sh

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#261](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/261/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/261/consoleText) for more details.
Possible conflicts:
  - PR #2323 dominikl 'Add install docs for ubuntu 22.04'
    - omero/sysadmins/unix/walkthrough/walkthrough_ubuntu2204.sh

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#262](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/262/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/262/consoleText) for more details.
Possible conflicts:
  - PR #2323 dominikl 'Add install docs for ubuntu 22.04'
    - omero/sysadmins/unix/walkthrough/walkthrough_ubuntu2204.sh

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#263](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/263/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/263/consoleText) for more details.
Possible conflicts:
  - PR #2323 dominikl 'Add install docs for ubuntu 22.04'
    - omero/sysadmins/unix/walkthrough/walkthrough_ubuntu2204.sh

--conflicts

**Comment by jburel** [comment]
Merging the changes. I will sort out the ubuntu PR manually

**Pull request merged**
