### PR TITLE
Update details on OMERO setup at IMCF / Biozentrum

### PR DESCRIPTION
**Pull request by ehrenfeu**
* update link to point directly to IMCF (where there is information about the OMERO instance)
* update amount of users and used storage space
* restructure (and update) resources a bit to make it more readable

### CODE REVIEW

**Review by sbesson — APPROVED** [review]
Thanks Niko

**Comment by joshmoore** [comment]
❤️

**Comment by sbesson** [comment]
@ehrenfeu it looks like https://www.biozentrum.unibas.ch/imcf has gone AWAL (`The requested page could not be found`). DO you know if the website is getting migrated and if yes what the new location is supposed to be?

**Comment by ehrenfeu** [comment]
Hi @sbesson - you're right, the website is *currently* being migrated. The link should be re-established afterwards, at least that was the point of having permanent deep-links...

Will keep an eye on it though, thanks!

**Comment by sbesson** [comment]
Thanks for the feedback and no problem. We'll temporarily ignore these broken links and get back to you in a few days/weeks if it's still 404

**Comment by ehrenfeu** [comment]
Works again now. Thanks for pointing this out, it had actually been forgotten in the migration...

**Pull request merged**
