### PR TITLE
OMERO model object reference

### PR DESCRIPTION
**Pull request by mtbc**
This is a newly created document that, as a developer, I've often wished I had. Staged at https://www.openmicroscopy.org/site/support/omero5-staging/developers/Model/EveryObject.html and fixes http://trac.openmicroscopy.org.uk/ome/ticket/12140.

--rebased-to #1081

### CODE REVIEW

**Comment by sbesson** [comment]
How did you generate the every object page?

**Comment by mtbc** [comment]
https://github.com/mtbc/openmicroscopy/commit/4825e5b44beb4802b6fb79771f2648a54d22173f more or less. Can certainly adjust formatting if need be, but it was hard to find anything more concise that Sphinx would actually permit.

**Comment by mtbc** [comment]
One thing I *can* do is to close up the properties section a bit at the cost of having the "used by" links link to the class, not the specific property, if that's preferable.

**Comment by mtbc** [comment]
Pushed an additional commit to show what I meant by the latest comment. Can be undone if preferred.

**Comment by hflynn** [comment]
Having both 'relationships' and 'properties' under each subheading in the side menu makes this very hard to navigate - could we remove the subheadings? The 'relationships' are self-explanatory and we could use a bullet point to mark the properties subsection instead.

**Comment by hflynn** [comment]
Being really nitpicky, I'd prefer 'properties are:' but this looks much better thanks! Can we also have 'Subclasses', Used by' and 'Properties' since these are new sentences? Otherwise, I'm happy with the formatting now.
What is the plan here for the page generation? Can this be merged and then an autogen PR opened @sbesson ?

**Comment by sbesson** [comment]
Definitely planning to have this auto-generated at some point. This won't make sense here since the first commit is so large. Also this will require a top-level PR to be opened by @mtbc.

**Comment by mtbc** [comment]
Will make the suggested changes. :smiley:

My plan is to get this and its rebase past review, then commit to develop the resulting OMERO.server class that generates them, and when the 5.1 model is finalized to submit an update docs PR to include those changes, then we oughtn't need it again until 5.2. Invocation is a bit nasty at the moment and I add the overview paragraph manually, but in the longer term I can work with @sbesson to help him to find some autogen approach that works.

**Comment by hflynn** [comment]
Ok, so this PR can be merged once the final nitpicks are sorted then? @mtbc do you want to make a card on Trello for your plan?

**Comment by hflynn** [comment]
Looks pretty good on staging to me, merging.

**Comment by mtbc** [comment]
Opened #1081 and https://github.com/openmicroscopy/openmicroscopy/pull/3404, and created https://trello.com/c/a1Utd8JL/404-update-everyobject-txt and https://trello.com/c/jfPrRneK/261-autogen-omero-object-reference.

**Pull request merged**
