### PR TITLE
Update auto-generated documentation

### PR DESCRIPTION
**Pull request by snoopycrimecop**
Repository: openmicroscopy/ome-documentation
Already up-to-date.

Generated by build [OMERO-DEV-latest-docs-autogen#288](https://ci.openmicroscopy.org/job/OMERO-DEV-latest-docs-autogen/288/).

---

--no-rebase

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-docs#220](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-docs/220/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-docs/220/consoleText) for more details.
Possible conflicts:
- PR #1391 jburel 'Pillow version'
  - omero/sysadmins/unix/walkthrough/step01_centos6_deps.sh
  - omero/sysadmins/unix/walkthrough/step01_centos6_py27_deps.sh

**Comment by sbesson** [comment]
Briefly discussed with @jburel. The auto-generated script currently adds all of the linux scripts from `omero-install` but we might want to streamline this. I don't know if that implies we should close this PR for now and either open a separate PR with the `omero/sysadmins/config.txt` changes only or include them as part of #1390.

**Comment by hflynn** [comment]
I've merged #1390 so Ola can fix her conflicting PR. Not sure how we want to handle this - fetch the branch and open a PR with just the config.txt changes?

**Comment by sbesson** [comment]
@hflynn I think we can manually create the diff for `omero/sysadmins/config.txt` and open a PR changing this files only.

**Comment by hflynn** [comment]
Okay thanks, shutting this and doing the config.txt changes manually now.

**Pull request closed without merging**
