### PR TITLE
Review description of all OMERO.matlab getter functions

### PR DESCRIPTION
**Pull request by sbesson**
- Specify the owner/group context for the various signatures
- Fix loaded graph information
- Add documentation about group/owner parameter/key value

Documents https://github.com/openmicroscopy/openmicroscopy/pull/3839

### CODE REVIEW

**Comment by jburel** [comment]
```To load the whole graph (projects, datasets, images), pass `true` as an optional argument::``` => Maybe we add a warning. Since that call could load a large amount of data

**Comment by jburel** [comment]
```To specify the owner or group of the projects...```: 
Not very clear
I will break it into 2 steps. 
 * To retrieve projects owned by a given member do...
 * To retrieve projects in a given group do...

**Comment by jburel** [comment]
```If the dataset identifiers are known, they can retrieved independently of``` => missing be they can be retrieved

**Comment by sbesson** [comment]
Pushed

**Comment by jburel** [comment]
Looks good. Merging

**Comment by sbesson** [comment]
--rebased-to #1273

**Pull request merged**
