### PR TITLE
Mention docker-example-omero on install pages

### PR DESCRIPTION
**Pull request by will-moore**
For any users who wish to find out about our support for Docker, it seems the best place to start is searching image.sc
https://forum.image.sc/search?q=docker%20omero

After reading a lot of those posts I eventually found https://github.com/ome/docker-example-omero.
This is also linked-to from https://www.openmicroscopy.org/explore/ but I never thought to start there. It seems the OMERO install docs are the best place to mention Docker support.

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#260](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/260/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/260/consoleText) for more details.
Possible conflicts:
  - PR #2291 pwalczysko 'Add ansible and docker install doc -  former "install.rst"'
    - omero/sysadmins/index.rst

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#261](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/261/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/261/consoleText) for more details.
Possible conflicts:
  - PR #2291 pwalczysko 'Add ansible and docker install doc -  former "install.rst"'
    - omero/sysadmins/index.rst

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#3](https://BRANCH-ci.openmicroscopy.org/jenkins/job/OMERO-docs/3/). See the [console output](https://BRANCH-ci.openmicroscopy.org/jenkins/job/OMERO-docs/3/consoleText) for more details.
Possible conflicts:
  - PR #2291 pwalczysko 'Add ansible and docker install doc -  former "install.rst"'
    - omero/sysadmins/index.rst
  - Upstream changes
    - omero/sysadmins/index.rst

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#367](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/367/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/367/consoleText) for more details.
Possible conflicts:
  - PR #2291 pwalczysko 'Add ansible and docker install doc -  former "install.rst"'
    - omero/sysadmins/index.rst
  - Upstream changes
    - omero/sysadmins/index.rst

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#4](https://BRANCH-ci.openmicroscopy.org/jenkins/job/OMERO-docs/4/). See the [console output](https://BRANCH-ci.openmicroscopy.org/jenkins/job/OMERO-docs/4/consoleText) for more details.
Possible conflicts:
  - PR #2291 pwalczysko 'Add ansible and docker install doc -  former "install.rst"'
    - omero/sysadmins/index.rst
  - Upstream changes
    - omero/sysadmins/index.rst

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#368](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/368/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/368/consoleText) for more details.
Possible conflicts:
  - PR #2291 pwalczysko 'Add ansible and docker install doc -  former "install.rst"'
    - omero/sysadmins/index.rst
  - Upstream changes
    - omero/sysadmins/index.rst

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#5](https://BRANCH-ci.openmicroscopy.org/jenkins/job/OMERO-docs/5/). See the [console output](https://BRANCH-ci.openmicroscopy.org/jenkins/job/OMERO-docs/5/consoleText) for more details.
Possible conflicts:
  - PR #2291 pwalczysko 'Add ansible and docker install doc -  former "install.rst"'
    - omero/sysadmins/index.rst
  - Upstream changes
    - omero/sysadmins/index.rst

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#369](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/369/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/369/consoleText) for more details.
Possible conflicts:
  - PR #2291 pwalczysko 'Add ansible and docker install doc -  former "install.rst"'
    - omero/sysadmins/index.rst
  - Upstream changes
    - omero/sysadmins/index.rst

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#6](https://BRANCH-ci.openmicroscopy.org/jenkins/job/OMERO-docs/6/). See the [console output](https://BRANCH-ci.openmicroscopy.org/jenkins/job/OMERO-docs/6/consoleText) for more details.
Possible conflicts:
  - PR #2291 pwalczysko 'Add ansible and docker install doc -  former "install.rst"'
    - omero/sysadmins/index.rst
  - Upstream changes
    - omero/sysadmins/index.rst

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#370](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/370/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/370/consoleText) for more details.
Possible conflicts:
  - PR #2291 pwalczysko 'Add ansible and docker install doc -  former "install.rst"'
    - omero/sysadmins/index.rst
  - Upstream changes
    - omero/sysadmins/index.rst

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#7](https://BRANCH-ci.openmicroscopy.org/jenkins/job/OMERO-docs/7/). See the [console output](https://BRANCH-ci.openmicroscopy.org/jenkins/job/OMERO-docs/7/consoleText) for more details.
Possible conflicts:
  - PR #2291 pwalczysko 'Add ansible and docker install doc -  former "install.rst"'
    - omero/sysadmins/index.rst
  - Upstream changes
    - omero/sysadmins/index.rst

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#371](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/371/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/371/consoleText) for more details.
Possible conflicts:
  - PR #2291 pwalczysko 'Add ansible and docker install doc -  former "install.rst"'
    - omero/sysadmins/index.rst
  - Upstream changes
    - omero/sysadmins/index.rst

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#8](https://BRANCH-ci.openmicroscopy.org/jenkins/job/OMERO-docs/8/). See the [console output](https://BRANCH-ci.openmicroscopy.org/jenkins/job/OMERO-docs/8/consoleText) for more details.
Possible conflicts:
  - PR #2291 pwalczysko 'Add ansible and docker install doc -  former "install.rst"'
    - omero/sysadmins/index.rst
  - Upstream changes
    - omero/sysadmins/index.rst

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#372](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/372/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/372/consoleText) for more details.
Possible conflicts:
  - PR #2291 pwalczysko 'Add ansible and docker install doc -  former "install.rst"'
    - omero/sysadmins/index.rst
  - Upstream changes
    - omero/sysadmins/index.rst

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#9](https://BRANCH-ci.openmicroscopy.org/jenkins/job/OMERO-docs/9/). See the [console output](https://BRANCH-ci.openmicroscopy.org/jenkins/job/OMERO-docs/9/consoleText) for more details.
Possible conflicts:
  - PR #2291 pwalczysko 'Add ansible and docker install doc -  former "install.rst"'
    - omero/sysadmins/index.rst
  - Upstream changes
    - omero/sysadmins/index.rst

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#374](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/374/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/374/consoleText) for more details.
Possible conflicts:
  - PR #2291 pwalczysko 'Add ansible and docker install doc -  former "install.rst"'
    - omero/sysadmins/index.rst
  - Upstream changes
    - omero/sysadmins/index.rst

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#375](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/375/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/375/consoleText) for more details.
Possible conflicts:
  - PR #2291 pwalczysko 'Add ansible and docker install doc -  former "install.rst"'
    - omero/sysadmins/index.rst
  - Upstream changes
    - omero/sysadmins/index.rst

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#376](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/376/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/376/consoleText) for more details.
Possible conflicts:
  - PR #2291 pwalczysko 'Add ansible and docker install doc -  former "install.rst"'
    - omero/sysadmins/index.rst
  - Upstream changes
    - omero/sysadmins/index.rst

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#377](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/377/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/377/consoleText) for more details.
Possible conflicts:
  - PR #2291 pwalczysko 'Add ansible and docker install doc -  former "install.rst"'
    - omero/sysadmins/index.rst
  - Upstream changes
    - omero/sysadmins/index.rst

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#378](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/378/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/378/consoleText) for more details.
Possible conflicts:
  - PR #2291 pwalczysko 'Add ansible and docker install doc -  former "install.rst"'
    - omero/sysadmins/index.rst
  - Upstream changes
    - omero/sysadmins/index.rst

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#379](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/379/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/379/consoleText) for more details.
Possible conflicts:
  - PR #2291 pwalczysko 'Add ansible and docker install doc -  former "install.rst"'
    - omero/sysadmins/index.rst
  - Upstream changes
    - omero/sysadmins/index.rst

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#380](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/380/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/380/consoleText) for more details.
Possible conflicts:
  - PR #2291 pwalczysko 'Add ansible and docker install doc -  former "install.rst"'
    - omero/sysadmins/index.rst
  - Upstream changes
    - omero/sysadmins/index.rst

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#10](https://BRANCH-ci.openmicroscopy.org/jenkins/job/OMERO-docs/10/). See the [console output](https://BRANCH-ci.openmicroscopy.org/jenkins/job/OMERO-docs/10/consoleText) for more details.
Possible conflicts:
  - PR #2291 pwalczysko 'Add ansible and docker install doc -  former "install.rst"'
    - omero/sysadmins/index.rst
  - Upstream changes
    - omero/sysadmins/index.rst

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#381](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/381/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-docs/381/consoleText) for more details.
Possible conflicts:
  - PR #2291 pwalczysko 'Add ansible and docker install doc -  former "install.rst"'
    - omero/sysadmins/index.rst
  - Upstream changes
    - omero/sysadmins/index.rst

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#11](https://BRANCH-ci.openmicroscopy.org/jenkins/job/OMERO-docs/11/). See the [console output](https://BRANCH-ci.openmicroscopy.org/jenkins/job/OMERO-docs/11/consoleText) for more details.
Possible conflicts:
  - PR #2291 pwalczysko 'Add ansible and docker install doc -  former "install.rst"'
    - omero/sysadmins/index.rst
  - Upstream changes
    - omero/sysadmins/index.rst

--conflicts

**Comment by will-moore** [comment]
Closing since this is covered by #2291

**Pull request closed without merging**
