### PR TITLE
add what's new note about Rect → Rectangle

### PR DESCRIPTION
**Pull request by mtbc**
Suggested by @jburel re. something on a docs card.

--no-rebase

### CODE REVIEW

**Comment by mtbc** [comment]
Ah, now found https://trello.com/c/2Mzfzvho/74-developer-doc-updates -- not that Trello bothered notifying me my name was there, bah!

**Comment by jburel** [comment]
just added your name after we spoke!!

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-docs#95](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-docs/95/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-docs/95/consoleText) for more details.
Possible conflicts:
  - Conflict detection failed
    - None

**Comment by mtbc** [comment]
To be cherry-picked onto #1313.

**Pull request closed without merging**
