### PR TITLE
autogen-doc

### PR DESCRIPTION
**Pull request by jburel**
Fix issue when generating omeroweb-install page

### CODE REVIEW

**Comment by jburel** [comment]
To check output, download zip from https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-docs-superbuild-build/52/

**Comment by will-moore** [comment]
I'm not quite sure what the "Fix issue" bug was, but the Unbuntu 16.04 and 18.04 all seem to have built correctly in the zip.

**Comment by will-moore** [comment]
Ah, I see ```OMERO=/opt/omero/web//bin/omero``` mentioned at https://github.com/ome/ome-documentation/pull/2067#issuecomment-567450717 about this PR, but I don't see any changes in e.g. omero/sysadmins/unix/install-web/walkthrough/omeroweb-install-debian9-ice3.6.rst:194: in this PR.

**Comment by jburel** [comment]
The file will not be updated. it will only be updated when we run autogen
The existing file will be changed.
The superbuild job runs autogen and the output generated is similar to what will be merged in this repo
Check the html pages in the zip and see if the path is correct no ``//``

**Comment by will-moore** [comment]
No ```//``` on this page https://py3-ci.openmicroscopy.org/jenkins/job/OMERO-docs/93/artifact/omero/_build/html/sysadmins/unix/server-ubuntu1804-ice36.html or the ubuntu1604 page.

**Comment by jburel** [comment]
you are looking at the wrong pages
You need to download the zip from https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-docs-superbuild-build/53/
and check the ubuntu web install pages

**Comment by will-moore** [comment]
No // there either! 👍

**Pull request merged**
