### PR TITLE
Linux walkthrough

### PR DESCRIPTION
**Pull request by jburel**
Prepare the links to support new naming of install scripts

### CODE REVIEW

**Comment by manics** [comment]
What would be nice is a cross-check of which files are copied by the autogen and which ones are included in the docs, so that if someone adds/removes a file from an external repo but doesn't update the docs it immediately causes an error.

**Comment by hflynn** [comment]
Ok, so does this need to be merged before the job can be fixed? Sorry, I've rather lost track of the plan here.

**Comment by jburel** [comment]
http://www.openmicroscopy.org/site/support/omero5.2-staging/sysadmins/unix/server-linux-walkthrough.html
Changes now on staging
We have one broken link for homebrew

**Comment by jburel** [comment]
The links have been fixed but the content needs to be reviewed

**Comment by hflynn** [comment]
This looks ok on staging. The technical content is all merged on omero-install already isn't it? I'd be inclined to merge and move on to the homebrew walk-through on a different PR and then restructuring separately.

**Comment by jburel** [comment]
All the files have been merged on omero-install

**Comment by hflynn** [comment]
Does your comment on #1342 mean you are planning more work here @jburel ? Or did you want input on whether to split this page up first?

**Comment by jburel** [comment]
not in this PR
I will start working on another one

**Comment by hflynn** [comment]
ok, shall I just merge this then and we can look at the content again on the new PR?

**Comment by jburel** [comment]
This one was only to fix the broken links. So yes please

**Pull request merged**
