### PR TITLE
CLI restructuring

### PR DESCRIPTION
**Pull request by sbesson**
See https://github.com/openmicroscopy/ome-documentation/pull/1146#issuecomment-83057548 for the genesis of this PR.

This PR does not modify existing content but re-organizes the structure of the CLI documentation. Main (breaking) changes are the following:
- the landing pages for each section of the CLI documentation are `users/cli/index.tx`, `sysadmins/cli/index.txt` and `developers/cli/index.txt`
- the large users and sysadmin CLI sections are split in separate pages (roughly per command) with a mini-toc in the landing page
- the Java command-line-importer section is moved as a subsection of the CLI import page
- the sysadmin Command line interface landing page is moved to the top-level of the sysadmin section under the installation sections

To review this PR, check everything builds as expected and that the new layout makes sense. Content for each page should be reviewed separately and is outside the scope of this PR.

--no-rebase

### CODE REVIEW

**Comment by sbesson** [comment]
For the impatient, see https://www.openmicroscopy.org/site/support/omero5.1-staging/users/cli/

**Comment by ximenesuk** [comment]
Structurally this looks fine to me. The rendering and layout are okay. Good to merge from me if it is okay by @hflynn and others.

**Comment by joshmoore** [comment]
Possibly for a follow-up PR but does this stuff need cleaning:
```
Sample config/importer.config INI file:
```

**Comment by sbesson** [comment]
Yes the CLI import file review is next on my list. And this will die :)

**Comment by hflynn** [comment]
Works for me, I will go through the non-sphinx pages and check where I'll need to fix links.

The DB page that is all version 4 is going to need updating too.

**Comment by hflynn** [comment]
We good to merge this then?

**Comment by sbesson** [comment]
Note there is a Trello card for going over the various pages https://trello.com/c/Lo6MKBRY/298-5-1-cli

**Comment by hflynn** [comment]
:+1:

**Pull request merged**
