### PR TITLE
Update auto-generated documentation

### PR DESCRIPTION
**Pull request by snoopycrimecop**
Repository: openmicroscopy/ome-documentation
Already up-to-date.

Generated by build [OMERO-DEV-latest-docs-autogen#861](https://ci.openmicroscopy.org/job/OMERO-DEV-latest-docs-autogen/861/).

----
--no-rebase

### CODE REVIEW

**Comment by jburel** [comment]
Closing This PR, dev-latest did not contain the history changes
Rebuilding dev-latest then will rebuild the doc

**Comment by hflynn** [comment]
Looks good on staging for now, will recheck once history propagates through

**Comment by jburel** [comment]
@hflynn history is in

**Comment by hflynn** [comment]
All looks good!

**Pull request merged**
