### PR TITLE
Fix missed webtest links on 5.2

### PR DESCRIPTION
**Pull request by hflynn**
See https://ci.openmicroscopy.org/view/Docs/job/OMERO-5.2-latest-docs/22/warnings3Result/

This PR manually rebases the changes from #1551 to the dev_5_2 branch because I started fixing the build and then remembered to check if I rebased the develop PR.

### CODE REVIEW

**Comment by hflynn** [comment]
Build is green - https://ci.openmicroscopy.org/view/Docs/job/OMERO-5.2-merge-docs/31/

**Comment by jburel** [comment]
`If you install the omero-webtest app` this should be `OMERO.webtest` app in omero/developers/Web/WritingTemplates.txt

**Comment by jburel** [comment]
The link to "figure" repo should also be fixed
in `contributing/ci-docs.txt`, `contributing/ci-release.txt`

**Comment by hflynn** [comment]
I haven't deleted the contributing folder on this branch but we only publish those docs from the develop branch. I'll push a commit to fix omero-webtest app now though, thanks.

**Comment by jburel** [comment]
Thanks @hflynn for clarification

**Pull request merged**
