### PR TITLE
Python docs update

### PR DESCRIPTION
**Pull request by will-moore**
Noticed when replying to:
http://lists.openmicroscopy.org.uk/pipermail/ome-users/2015-November/005727.html

And adds line and point examples, bringing ROIs up to date with https://github.com/openmicroscopy/openmicroscopy/pull/4331

### CODE REVIEW

**Comment by ximenesuk** [comment]
It might be worth using this PR to update the comment and print statements from https://github.com/openmicroscopy/ome-documentation/pull/1332/files#diff-5ffe001066c8ef14da7c3771965aa569R794 to reflect multiple shapes.

**Comment by ximenesuk** [comment]
Otherwise the changes look reasonable.

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-docs#125](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-docs/125/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-docs/125/consoleText) for more details.
Possible conflicts:
- PR #1331 mtbc 'update Rect to Rectangle in OMERO model object glossary'
  - omero/developers/Python.txt

**Comment by hflynn** [comment]
@mtbc 's PR is merged now so you can merge develop into this and resolve the conflict

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-docs#126](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-docs/126/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-docs/126/consoleText) for more details.
Possible conflicts:
- Upstream changes
  - omero/developers/Python.txt

**Comment by hflynn** [comment]
@ximenesuk can you sign off on whether this is good to merge now please?

**Comment by ximenesuk** [comment]
THis looks good to merge.

**Pull request merged**
