### PR TITLE
Link to OMERO.web developer docs

### PR DESCRIPTION
**Pull request by ctrueden**
The "built-in lightweight Django development server" is mentioned on the main OMERO.web installation page, but with no explanation of what it is or how to use it. This patch links to the dedicated page in the developer documentation section, for those who wish to know more.

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#997](https://ci.openmicroscopy.org/job/OME-5.1-merge-push/997/). See the [console output](https://ci.openmicroscopy.org/job/OME-5.1-merge-push/997/consoleText) for more details.
Possible conflicts:
  - PR #1190 hflynn 'Public repo docs'
    - omero/sysadmins/unix/install-web.txt
    - omero/sysadmins/windows/install-web.txt

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#999](https://ci.openmicroscopy.org/job/OME-5.1-merge-push/999/). See the [console output](https://ci.openmicroscopy.org/job/OME-5.1-merge-push/999/consoleText) for more details.
Possible conflicts:
  - PR #1190 hflynn 'Public repo docs'
    - omero/sysadmins/unix/install-web.txt
    - omero/sysadmins/windows/install-web.txt

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-5.1-merge-docs#519](https://ci.openmicroscopy.org/job/OMERO-5.1-merge-docs/519/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-5.1-merge-docs/519/consoleText) for more details.
Possible conflicts:
  - PR #1190 hflynn 'Public repo docs'
    - omero/sysadmins/unix/install-web.txt
    - omero/sysadmins/windows/install-web.txt

**Comment by sbesson** [comment]
Thanks @ctrueden.

**Pull request merged**
