### PR TITLE
Fixing broken anchor link

### PR DESCRIPTION
**Pull request by hflynn**
Existing link was making http://ci.openmicroscopy.org/view/Docs/job/OMERO-5.1-merge-docs/ yellow and when I hunted around, I found the topic was actually on a different page.

cc @aleksandra-tarkowska - if you are happy with this, I'll rebase to dev_5_0 once the build is green.

### CODE REVIEW

**Comment by aleksandra-tarkowska** [comment]
@hflynn I think it should be https://docs.djangoproject.com/en/1.6/topics/templates/#template-inheritance

**Comment by aleksandra-tarkowska** [comment]
Looks like we need to check if we have more links like https://docs.djangoproject.com/en/dev/, they should all be 1.6 rather then dev

**Comment by sbesson** [comment]
```
$ git grep "docs.djangoproject.com/en/dev" | wc
       5      15     608
```

Time to create a `djangodocs` extlink? This will also simplify maintenance the day we bump our Django version.

**Comment by aleksandra-tarkowska** [comment]
@sbesson great idea, what is the best strategy to do it?

**Comment by hflynn** [comment]
I'll do that on this PR, thanks for pointing that out @aleksandra-tarkowska

**Comment by hflynn** [comment]
I left one /dev/ link because it was to the 1.5 notes instead.

**Comment by hflynn** [comment]
Ok, I've got extra '/' in the links, I'll fix that after stand-up (realised after I left yesterday, bah!)

**Comment by sbesson** [comment]
I would use this PR to find and replace all links to the django documentation using your new extlink:

```
$  git grep "docs.djangoproject.com/en" | wc
      22     175    3742
```

**Comment by hflynn** [comment]
Ah, I only grepped for /en/dev/ - I'll fix this up this afternoon

**Comment by hflynn** [comment]
Ok, aside from the 1.5 one already mentioned, that is all of them except those in the config.txt which I'll need to open a PR on the code base tomorrow to fix.

**Comment by sbesson** [comment]
https://ci.openmicroscopy.org/job/OMERO-5.1-merge-docs/ is green. :+1: Anything else on this PR?

**Comment by hflynn** [comment]
I hadn't planned to add anything unless someone spotted a mistake I missed.

**Comment by aleksandra-tarkowska** [comment]
I am good

**Comment by hflynn** [comment]
--rebased-to #1067

**Pull request merged**
