### PR TITLE
exclude failing link

### PR DESCRIPTION
**Pull request by jburel**
Excludes links currently failing the daily build

### CODE REVIEW

**Comment by jburel** [comment]
https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-docs/ is green

**Comment by will-moore** [comment]
Broken links in https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-docs/1332/console seem to be fixed. Strange as https://wiki.centos.org/About/Product and https://wiki.centos.org/HowTos/SELinux seem to be fine, but 👍 for getting build green.

**Comment by jburel** [comment]
they were fine the day I tested it but the build was still failing.
I will exclude the PR for tomorrow's build and see the outcome

**Comment by jburel** [comment]
Seen again on latest-ci

**Pull request merged**
