### PR TITLE
change help for docs to use HTTPS

### PR DESCRIPTION
**Pull request by mtbc**
See https://trello.com/c/mTAsiIpK/4014-help-website-has-bad-certificate.

### CODE REVIEW

**Comment by manics** [comment]
There are still some references to `http://help`:
```
$ git grep http://help
contributing/ci-docs.rst:                  http://help.staging.openmicroscopy.org
contributing/ci-docs.rst:                  http://help.openmicroscopy.org
contributing/jekyll.rst:- `OME Help site <http://help.openmicroscopy.org/>`_
contributing/jekyll.rst:`help.openmicroscopy.org <http://help.openmicroscopy.org>`_ covers OMERO user
contributing/jekyll.rst:site will be viewable at `<http://help.staging.openmicroscopy.org>`_.
omero/developers/scripts/index.rst:`GitHub app for your OS <http://help.github.com/articles/set-up-git>`_
omero/sysadmins/config.rst:Default: `[["Data", "webindex", {"title": "Browse Data via Projects, Tags etc"}],["History", "history", {"title": "History"}],["Help", "http://help.openmicroscopy.org/",{"title":"Open OMERO user guide in a new tab", "target":"new"}]]`
omero/sysadmins/installing-scripts.rst:the `GitHub app for your OS <http://help.github.com/articles/set-up-git>`_
```

**Comment by manics** [comment]
(In future this should be done for all other http URLs where https is supported by the domain)

**Comment by mtbc** [comment]
There are. I wasn't sure if things like `config.rst` are generated from OMERO source and the other links seem to be more about how the site works in CI and whatnot rather than links for people wanting help; I thought it might be intentional they don't use the `:help:` markup. Basically, I stuck to what I was sure of, figuring it's at least an improvement.

**Comment by mtbc** [comment]
Given other priorities maybe just merge as-is: https://trello.com/c/z0MqRssM/459-more-https-links captures the larger to-do.

**Pull request merged**
