### PR TITLE
Fix link to Homebrew installation script (rebased onto dev_5_0)

### PR DESCRIPTION
**Pull request by sbesson**
This is the same as gh-1091 but rebased onto dev_5_0.

----

With the migration of the script to the omero-install repository, the
link on the documentation page needs to be updated

### CODE REVIEW

**Comment by sbesson** [comment]
--rebased-from #1091

**Comment by sbesson** [comment]
See https://github.com/ome/omero-install/pull/11

**Comment by rleigh-dundee** [comment]
This also looks fine.  Please merge.

**Comment by rleigh-dundee** [comment]
Actually, the docs merge build has broken link for me: https://github.com/snoopycrimecop/openmicroscopy/blob/merge/dev_5_0/latest/https://github.com/ome/omero-install/tree/master/homebrew  (in http://www.openmicroscopy.org/site/support/omero5-staging/sysadmins/unix/server-install-homebrew.html)

**Comment by sbesson** [comment]
My bad. Pushed a fix.

**Comment by rleigh-dundee** [comment]
Thanks, that's much better.

**Comment by rleigh-dundee** [comment]
Looks good to merge.

Note that this page is quite outdated and could do some work for 5.1:
- OSX/Xcode section describes the old CI setup which was replaced a while back
- "Java..comes as standard on OS X" has not been true since 10.6 and could be removed.
- System vs. homebrew python.  Rather than detailing all the various combinations which are possible, maybe just recommend use of homebrew python and leave it at that?

Most of this is duplication what's already on the main unix installation page, which also covers installing the prerequisites with homebrew.  Could this page be cut down to just how to do the install and delegate the rest of the detail to the main page?

**Comment by hflynn** [comment]
Great suggestion @rleigh-dundee - I'll stick a card on the Docs board for that, if you or Seb want to volunteer, please go ahead :)

**Pull request merged**
