### PR TITLE
DropBox Unicode configuration section

### PR DESCRIPTION
**Pull request by ximenesuk**
This PR adds a short section to the docs advising on how to customise the PYthon configuration to deal with Unicode charactewrs in path and file names.
See: https://trello.com/c/lFY8DI8Z/20-unicode-in-upgrade

### CODE REVIEW

**Comment by mtbc** [comment]
Staged at http://www.openmicroscopy.org/site/support/omero5.2-staging/sysadmins/dropbox.html#unicode-path-and-file-names.

**Comment by ghost** [comment]
The text and HTML page look fine and good to merge.

The only question I have here is why this isn't the default behaviour?  It seems like having it able to process Unicode filenames is an expected default, not a special-case customisation.

**Comment by ximenesuk** [comment]
@rleigh-dundee It isn't the default because @joshmoore and I battled long and hard trying various solutions without success. This local customisation was the only thing that worked without breaking other things. An eventual move to Python 3 would remove the problem but for now this seemed to be the best fix without major changes to the code.

**Comment by ximenesuk** [comment]
@joshmoore are you okay with this being merged?

**Comment by joshmoore** [comment]
Happy for it to be merged. Thinking back, I already can't remember the various conditions under which it happens/happened. If you remember something like "when locale=X,..." that may be useful to include so that users don't assume they _always_ have to make this setting.

**Comment by ximenesuk** [comment]
@joshmoore I've been unable to find anything obvious in the various forum threads and cards that might help here.

**Comment by joshmoore** [comment]
Fair enough.

**Pull request merged**
