### PR TITLE
Add cp/_rm section for 5.0.7

### PR DESCRIPTION
**Pull request by joshmoore**
See: https://github.com/openmicroscopy/openmicroscopy/pull/3379

### CODE REVIEW

**Comment by ximenesuk** [comment]
This looks good but in looking at the built docs I noticed that the, not strictly in-place, transfer option "upload_rm" isn't yet documented so this might be a good PR for that to sit in. The comparison between the "cp" group and the "ln" group is fine but why "cp" over "upload"? That comparison should be stated somewhere hereabouts too.

**Comment by joshmoore** [comment]
Happy to add in `upload_*`. Guess the only real optimization would be performance, though I haven't tested it. Assuming, say, a 1TB file, I'd think a simple `cp` would be much healthier.

**Comment by joshmoore** [comment]
@ximenesuk : copied the minimal blurb from https://github.com/openmicroscopy/ome-documentation/pull/975, but obviously you did much more there. Do we want to go further? /cc @hflynn

**Comment by ximenesuk** [comment]
Looks good to me. A sentence hinting at the benefits of `cp` might head off any questions but if we have no concrete metrics then maybe leave that for now? I'm happy either way.

**Comment by joshmoore** [comment]
I'm inclined to keep it a bit simple for 5.0.7. During the rebase, I'll see if it can be more tightly tied into your other fixes. @hflynn, this is all yours.

**Comment by hflynn** [comment]
Erm, sorry to come at this late but if this isn't actually in-place import stuff, would it not be better documented on https://www.openmicroscopy.org/site/support/omero5-staging/sysadmins/import-scenarios.html or at least signposting further up the page ?

**Comment by joshmoore** [comment]
`cp` and `cp_rm` is definitely in-place. `upload` and `upload_rm` work both via in-place and non-in-place (out-of-place? at-home?)

**Comment by hflynn** [comment]
Ah ok, sorry, I obviously got the wrong end of the stick.

**Comment by hflynn** [comment]
Re-running the merge build now but this is looking fine to me in that case. I'm inclined to agree about leaving the extra stuff on 5.1.0 only since we already decided not to rebase #975

**Comment by ximenesuk** [comment]
Yes, I think in-place may now be a misplaced term! All 5.x imports are effectively in-place in effect, it's just what you do before and after the import that differs!

**Comment by hflynn** [comment]
We do like to pick our terminology!

**Comment by hflynn** [comment]
Looks fine on staging. merging.

**Comment by joshmoore** [comment]
--rebased-to #1087

**Pull request merged**
