### PR TITLE
Ignore microsoft link with failing SSL cert

### PR DESCRIPTION
**Pull request by hflynn**
Temporarily ignore this link as it's making the merge build red

### CODE REVIEW

**Comment by hflynn** [comment]
Okay, I have no idea what is going on with the build, but it's not finding this at the all and continuing to report the broken link :(

**Comment by joshmoore** [comment]
It's likely the parentheses. Replacing them with `.`s or escaping them with `\` should work.

**Comment by hflynn** [comment]
Ah, finally green now!

**Comment by hflynn** [comment]
Latest build is green without this included so the issue is still on-going today - going to merge for the 5.4.5 release

**Pull request merged**
