### PR TITLE
expand discussion of binary repo setup for in-place import

### PR DESCRIPTION
**Pull request by mtbc**
See discussion on https://trello.com/c/SsE1sGqR/184-in-place-import-doc-is-unclear. Staged at https://ci.openmicroscopy.org/job/OMERO-DEV-merge-docs/ws/src/omero/_build/html/sysadmins/in-place-import.html#additional-setup-requirements.

### CODE REVIEW

**Review by joshmoore — COMMENTED** [review]
I like the change. Very clear and objective, but also broad enough someone must take responsibility for the implementation.

**Comment by pwalczysko** [comment]
Re [no-one](https://github.com/openmicroscopy/ome-documentation/pull/1873/files#diff-a9898c07fe215ecaac51af6fdcfa97dcR110) - grammarly says this is uncommon, and it is best to stick to the two words version (``no one``). Btw I know this was not changed in this PR, but it is in the same doc.

**Comment by pwalczysko** [comment]
Downloading this [service file](https://github.com/openmicroscopy/ome-documentation/pull/1873/files#diff-a9898c07fe215ecaac51af6fdcfa97dcR192) is a loss of time, cannot read it, cannot open it in Chrome or sublime text, why is it there ? How am I supposed to consume this information ?

(Note: I treid to download this file also from the released docs on 5.4.5, but with the same negative results)

**Comment by mtbc** [comment]
Not planning to fix the service file issue.

**Comment by pwalczysko** [comment]
Reads nice. Ready to merge FMPOV

**Pull request merged**
