### PR TITLE
Add link to example NGINX redirects

### PR DESCRIPTION
**Pull request by hflynn**
Adds the example @kennethgillen suggested on #1830

### CODE REVIEW

**Comment by kennethgillen** [comment]
@hflynn - nice one, thank you.

**Comment by hflynn** [comment]
Rebuilding merge docs now

**Comment by hflynn** [comment]
Staged at https://ci.openmicroscopy.org/view/Docs/job/OMERO-DEV-merge-docs/991/ and build is green

**Comment by mtbc** [comment]
Staged at https://ci.openmicroscopy.org/job/OMERO-DEV-merge-docs/ws/src/omero/_build/html/sysadmins/public.html#configuring-urls and looks good to me.

There's a question of if/how to link to a specific version of the playbook: there I have no strong opinion against any of the options.

**Review by mtbc — APPROVED** [review]

**Comment by hflynn** [comment]
Re-run the builds just to recheck but all fine so merging with Mark's thumbs up

**Comment by joshmoore** [comment]
I'm worried about this strategy. For the moment, this makes complete sense and clearly identifies what we're talking about. But as we evolve this file (which we will be doing), what warns/reminds us that this line needs to be updated?

**Comment by kennethgillen** [comment]
If we've linked to at least one method of achieving this, does it _need_ to stay current? 

e.g. if we changed the wording to say " You can find an example of configuration we've used for this
 +example" ?

**Comment by joshmoore** [comment]
"an example" would be better. If there's a bug though, or we change strategy, we may not want people copying-n-pasting from this file.

**Comment by hflynn** [comment]
@joshmoore that's why I updated the link to point at the line in a commit so that the content will stay static. The example illustrates what we're talking about, so it doesn't need to be updated.

**Comment by hflynn** [comment]
If we change strategy, we'll likely to be updating the doc page, in which case we'll have the link here to know to update it

**Comment by joshmoore** [comment]
But we won't know when changing prod-playbooks to look here for whether or not a change is needed. I did a search for `blob` throughout our code base and for the bigger repos, couldn't find any use of `blob/$commit` (as opposed to `blob/$branch` or `blob/$tag`). Discussing with @kennethgillen, I propose we add a tag and specify a bit better what it is we're linking to. I'll open momentarily.

**Comment by kennethgillen** [comment]
NB Josh suggested we try linking to >1 lines: tried this out and the URL API supports this, e.g. 
https://github.com/openmicroscopy/prod-playbooks/blob/2c73f0482bb87dc67e8d011d087ae591ad0bd836/nightshade-webclients.yml#L181-L183

**Comment by hflynn** [comment]
Happy to amend to a tag and wider line range, just let me know the new link

**Pull request merged**
