### PR TITLE
Ubuntu install

### PR DESCRIPTION
**Pull request by jburel**
Combine installation of OMERO and its dependencies on ubuntu 14.04 and 16.04
This replaces gh-1613

cc @hflynn

### CODE REVIEW

**Review by hflynn — APPROVED** [review]
All looks good on staging

**Comment by hflynn** [comment]
Not related to this PR but I'm still seeing a bunch of OMERO 5.2 references in the inserted bits from omero-install (e.g. https://www.openmicroscopy.org/site/support/omero5.3-staging/sysadmins/unix/server-install-homebrew.html#omero-release-server) and also https://www.openmicroscopy.org/site/support/omero5.3-staging/sysadmins/unix/server-centos6-ice36.html#ice-3-6 still seems to be referencing ice 3.5 - are there still omero-install updates needed?

**Comment by hflynn** [comment]
https://github.com/openmicroscopy/ome-documentation/blob/develop/omero/sysadmins/unix/server-centos6-ice36.txt#L57 - ice 3.5 reference is coming from 'walkthrough/walkthrough_centos6_py27_ius.sh'

**Comment by jburel** [comment]
Reference to ice 3.5 for centOS has been fixed in gh-1616

**Comment by jburel** [comment]
Commands to install for ice36 fixed for ubuntu by e8708ca

**Comment by jburel** [comment]
The "5.2" ref was due to version in omero-install. I have opened a PR https://github.com/ome/omero-install/pull/141, waiting for travis to complete.

**Review by hflynn — APPROVED** [review]
Changes on this PR look good, further omero-install issues need not block it so merging, thanks.

**Pull request merged**
