### PR TITLE
Simplify and update EditingOmeroWeb.rst

### PR DESCRIPTION
**Pull request by will-moore**
PR to update web development docs as part of Training.

More edits to come depending on the outcomes of https://trello.com/c/VdQ4HAl6/65-using-nginx-in-development

TODO:
 - [ ] Add my build script to docs https://gist.github.com/will-moore/bbcb487b99502e9275c4fc6d80fb3b9c after cleaning up (use params instead of hard-coded paths) as suggested in https://github.com/ome/presentations/pull/70 discussion.

### CODE REVIEW

**Comment by hflynn** [comment]
Are you expecting to finish this before the xmas break @will-moore ?

**Comment by will-moore** [comment]
This could be considered done for now.
The only question is whether to move my full build script https://gist.github.com/will-moore/bbcb487b99502e9275c4fc6d80fb3b9c into this page, but it needs cleaning-up to remove hard-coded paths etc.

**Review by rgozim — APPROVED** [review]

**Comment by hflynn** [comment]
Are you planning to add that script on this PR @will-moore or shall I merge this and leave you to card that extra action?

**Comment by jburel** [comment]
we cannot use that script in our doc.

**Comment by hflynn** [comment]
Merging in that case, thanks for the clarification J-M

**Pull request merged**
