### PR TITLE
Rephrase JMX target doc

### PR DESCRIPTION
**Pull request by hflynn**
See https://trello.com/c/vNz5ejDW/20-jmx-target-docs-arent-quite-correct

### CODE REVIEW

**Comment by joshmoore** [comment]
No objections to the wording, but it may be as easy to just allow setting the properties as it is to explain how to modify the XML: https://github.com/openmicroscopy/openmicroscopy/blob/develop/etc/templates/grid/templates.xml#L176

**Comment by hflynn** [comment]
Does that mean you want me to rewrite the next sentence too? Happy to do so if you have a suggestion

**Comment by joshmoore** [comment]
Only when/if there's a merged code change. Leaving to you if you want to do that here or elsewhere.

**Comment by hflynn** [comment]
Ahhh, I get you now. Seems unlikely there'll be a code change there for 5.4.4 unless that's something you want to get in @jburel ?

**Comment by jburel** [comment]
From this morning discussion I don't think @manics or @kennethgillen will work on it for 5.4.4.
I will confirm tomorrow

**Comment by manics** [comment]
I've no idea what the code change is

**Comment by joshmoore** [comment]
The code change would be to make `jmxhost` and `jmxport` configurable (likely via `omero.jmx.host` and `omero.jmx.port`). One catch is that if we want to enable for PixelData and Indexer (or in the future for microservices) then we need more than 1 port.

**Comment by manics** [comment]
In case it's relevant the IDR uses a javaagent:
- https://github.com/IDR/deployment/blob/IDR-0.4.4/ansible/management-prometheus.yml#L32
- https://github.com/IDR/deployment/blob/IDR-0.4.4/ansible/management-prometheus.yml#L95

**Comment by joshmoore** [comment]
Happy with this change. Getting this in, and we can examine wider JMX changes later.

**Pull request merged**
