### PR TITLE
fix broken webtest links

### PR DESCRIPTION
**Pull request by atarkowska**
fix broken webtest links

### CODE REVIEW

**Comment by hflynn** [comment]
https://ci.openmicroscopy.org/view/Docs/job/OMERO-DEV-merge-docs/458/ green for now but a second round of renaming still to do I gather so depending on timing, might be easier to keep this open and update it rather than merge and then open another PR.

**Comment by aleksandra-tarkowska** [comment]
fine by me

**Comment by atarkowska** [comment]
if that is not merged and rebased then latest (and 5.2) will fail, no?

**Comment by hflynn** [comment]
--rebased-to #1528

**Pull request merged**
