### PR TITLE
add transforms and projection defs to model object glossary

### PR DESCRIPTION
**Pull request by mtbc**
Updates the list of every object following,
- https://github.com/openmicroscopy/openmicroscopy/pull/4705
- https://github.com/openmicroscopy/openmicroscopy/pull/4672
- https://github.com/openmicroscopy/openmicroscopy/pull/4762
- https://github.com/openmicroscopy/openmicroscopy/pull/4781

Staged at http://www.openmicroscopy.org/site/support/omero5.3-staging/developers/Model/EveryObject.html.

### CODE REVIEW

**Comment by jburel** [comment]
ProjectionAxis is not listed.

**Comment by mtbc** [comment]
http://www.openmicroscopy.org/site/support/omero5.3-staging/developers/Model/EveryObject.html#projectionaxis

**Comment by jburel** [comment]
Thanks missed it in the collection of items.

**Comment by joshmoore** [comment]
NB: This type of PR looks like a prime snoopy candidate :)

**Comment by sbesson** [comment]
From what I recall, the primary limitation to simply including this generation in the autogen_docs script is that is requires a running server.

**Comment by hflynn** [comment]
Is this good to merge?

**Comment by joshmoore** [comment]
WFM

**Pull request merged**
