### PR TITLE
Update auto-generated documentation

### PR DESCRIPTION
**Pull request by snoopycrimecop**
Repository: openmicroscopy/ome-documentation
Already up-to-date.

Generated by build [OMERO-DEV-latest-docs-autogen#774](https://ci.openmicroscopy.org/job/OMERO-DEV-latest-docs-autogen/774/).

----
--no-rebase

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-DEV-merge-docs#650](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-docs/650/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-DEV-merge-docs/650/consoleText) for more details.
Possible conflicts:
  - PR #1647 hflynn '5.3.0 version history'
    - omero/users/history.txt

**Comment by hflynn** [comment]
@jburel not sure what the best way to handle this is - shall i merge this and rebase my version history PR on top of it?

**Comment by jburel** [comment]
Should the version history only be opened against openmicroscopy? since the autogen script takes care of copying the content

**Comment by hflynn** [comment]
D'oh! Ok, I need to fix #1647

**Pull request merged**
