### PR TITLE
python version requirement

### PR DESCRIPTION
**Pull request by jburel**
Clarify python version requirement
See https://github.com/openmicroscopy/openmicroscopy/pull/5321

cc @mtbc @sbesson

### CODE REVIEW

**Comment by mtbc** [comment]
Staged at http://www.openmicroscopy.org/site/support/omero5.3-staging/sysadmins/version-requirements.html#python.

**Comment by mtbc** [comment]
Is it possible to cause an in-cell linebreak before the checkmark?

reqs

**Comment by mtbc** [comment]
(If not then **good to merge**! The row will disappear for 5.4 anyway.)

**Comment by jburel** [comment]
The icons are aligned on staging, not much we can do in the "sphinx" table

**Comment by mtbc** [comment]
I was looking on staging; seems to depend on browser width. But if not much we can do then fine as-is.

**Comment by jburel** [comment]
@mtbc I have used bullet list and reference
let me know if it is better

**Comment by mtbc** [comment]
Alas, the indent from the list makes it worse overall: go ahead and revert or force-push that latest commit away and merge up to https://github.com/openmicroscopy/ome-documentation/pull/1698/commits/aae7b3bfe68857f5c0aba6b5aebac9fc07db4580. Thank you for trying!

**Comment by jburel** [comment]
i will remove the bullet point and keep the ref

**Comment by mtbc** [comment]
Feel free to relist for me, we'll get there in the end!

**Review by mtbc — APPROVED** [review]

**Pull request merged**
