### PR TITLE
Fix link to example scripts

### LINKED ISSUE #2189: Link to example server scripts not found
The `ome/omero-example-scripts` repository doesn't exist any longer, so the link https://docs.openmicroscopy.org/omero/5.6.3/developers/scripts/index.html#finding-scripts is broken.

### PR DESCRIPTION
**Pull request by dominikl**
Fixes https://github.com/ome/omero-documentation/issues/2189 

Just fix broken link to example scripts repo.

### CODE REVIEW

**Review by sbesson — APPROVED** [review]

**Comment by joshmoore** [comment]
@sbesson : was there a reason that this repo didn't get migrated to github.com/ome? I'm not remembering one.

**Comment by sbesson** [comment]
I think the primary reason is that this repository was forked from https://github.com/ome/omero-user-scripts and there is (was?) no possibility for an organization to fork itself.
In modern GitHub, I assume the forking would have bene replaced by using  templates.

**Comment by joshmoore** [comment]
Probably something like that but with all the migrations from `openmicrosopy` to `ome` we could have transferred, no?

**Comment by sbesson** [comment]
This is the error message I get when trying to transfer

Screenshot 2021-08-04 at 09 43 29

We need to remove the repo from the network but I haven't investigated this further.

**Pull request merged**
