### PR TITLE
Add double and timestamp MATLAB annotations functions to the table

### PR DESCRIPTION
**Pull request by sbesson**
This Pull Request adds the new annotations utility functions and a link to the `WriteData` example to the MATLAB developer page.

### CODE REVIEW

**Comment by sbesson** [comment]
--depends-on https://github.com/openmicroscopy/openmicroscopy/pull/3304

**Comment by hflynn** [comment]
The table is really wide (not that I think there is much we can do about that) but all renders fine on staging. @jburel do you want to review any technical content when you are happy with the code PR?

**Comment by sbesson** [comment]
@hflynn: as briefly mentioned in #3304, this table will still grow (need to add `long`, maybe `boolean`, `term` and `list` as well as `map`).
If we want to preserve the table, I am happy to swap the rows/columns to prevent uncontrolled width expansion. If you think this table does not add much value, I can alternatively link to the source folder and give a couple of examples.

**Comment by jburel** [comment]
@hflynn: i will have a look.

**Comment by hflynn** [comment]
Ah. The table is already too wide for my laptop screen, and swapping the rows/columns is still going to make it wider again. At the point at which you need to scroll, I'm not sure it adds any value.

**Comment by sbesson** [comment]
@hflynn: as discussed, last commit should remove the table which is becoming not manageable.

**Comment by jburel** [comment]
```
To create a file annotations from the content of a ``local_file_path`` and
 attach it to the image ``image_id``::
 
     fileAnnotation = writeFileAnnotation(session, local_file_path);
-    link = linkAnnotation(session, fileAnnotation, 'image', image_id);
```
Since you removed the link section. the text   "attach it to the image ``image_id``" should also be removed. You explain after how to link annotation

**Comment by sbesson** [comment]
Pushed

**Comment by hflynn** [comment]
All looks good to me

**Comment by sbesson** [comment]
--rebased-to #1073

**Pull request merged**
