### PR TITLE
ignore logback URLs

### PR DESCRIPTION
**Pull request by joshmoore**
Cert expired 2 days ago

see: https://py3-ci.openmicroscopy.org/jenkins/job/OMERO-docs/88/console

### CODE REVIEW

**Comment by mtbc** [comment]
I think they replaced it though it took a while for caches to catch up.

**Comment by joshmoore** [comment]
I'm still getting insecure locally.

**Comment by joshmoore** [comment]
Docs are green again.

**Comment by joshmoore** [comment]
latest-ci passed today without this. Closing.

**Pull request closed without merging**
