### PR TITLE
Install indexes

### PR DESCRIPTION
**Pull request by hflynn**
In lieu of restructuring in a point release, this tries to make the installation index page clearer
see https://trello.com/c/YhIMg4wf/50-unix-index-html-improvements

### CODE REVIEW

**Comment by jburel** [comment]
Looks good.

**Comment by joshmoore** [comment]
```
OMERO.server Mac OS X installation walk-through with Homebrew
OMERO.server installation on Ubuntu and Centos7
OMERO.server installation on Centos 6 with Python 2.7 and Ice 3.5
```

"...installation on OS X with Homebrew" ? or are the pages sufficiently different to warrant a different pattern?

**Comment by hflynn** [comment]
Good to merge now?

**Comment by joshmoore** [comment]
No objections from me (naturally). There was some suggestion today that the OS X page was more developer-focused. Not sure if that can/should impact the index.

**Comment by hflynn** [comment]
I think quite a lot of the sysadmin content is only divided from developer content by a very fine line. The page is clearly defined at the top and where it is linked, I think that'll do for now.

**Pull request merged**
