### PR TITLE
Document new OMERO_SESSIONDIR environment variable

### PR DESCRIPTION
**Pull request by sbesson**
This should replace the deprecated OMERO_SESSION_DIR envvar
Documents code changes in https://github.com/openmicroscopy/openmicroscopy/pull/3742

### CODE REVIEW

**Comment by sbesson** [comment]
@manics @joshmoore @kennethgillen : last commit should add a note explaining how to upgrade from OMERO_SESSION_DIR to OMERO_SESSIONDIR for 5.1.1+

**Comment by hflynn** [comment]
Looks like Travis needs a kick

**Comment by hflynn** [comment]
Travis seems determined to gripe about this, I'll check it locally if needed once code PR is merged.

**Comment by manics** [comment]
Good to merge

**Pull request merged**
