### PR TITLE
Update auto-generated documentation

### PR DESCRIPTION
**Pull request by snoopycrimecop**
Repository: openmicroscopy/ome-documentation
Already up-to-date.

Generated by build [OMERO-DEV-latest-docs-autogen#623](https://ci.openmicroscopy.org/job/OMERO-DEV-latest-docs-autogen/623/).

----
--no-rebase

### CODE REVIEW

**Comment by hflynn** [comment]
Still needs version history to go in

**Comment by jburel** [comment]
The version history in openmicroscopy is in.
I will copy the content to the doc.

**Comment by hflynn** [comment]
This build should update it once the latest code build is completed

**Comment by hflynn** [comment]
This build will be green when updated once https://github.com/openmicroscopy/openmicroscopy/pull/4966 is merged and then #1578 won't be needed @jburel

**Comment by hflynn** [comment]
Or I can just sort the docs out tomorrow once the code is tagged

**Comment by jburel** [comment]
closing for now
we can sort out the doc tomorrow

**Pull request closed without merging**
