### PR TITLE
add note about needing mock module for tables tests

### PR DESCRIPTION
**Pull request by mtbc**
Says what to do if `tables.test()` fails with the mock error. Cc: @bramalingam.

### CODE REVIEW

**Comment by rleigh-codelibre** [comment]
Looks fine and good to merge, thanks.

**Comment by jburel** [comment]
After the numpy/pillow saga, the decision was to avoid installation from pypi when possible
e.g. for ubuntu use ``apt-get install python-mock``.

**Comment by mtbc** [comment]
Adjusted accordingly, thank you. (Certainly don't want to get into a per-OS discussion in a brief note though!)

**Comment by jburel** [comment]
@mtbc Thanks for the adjustment

**Pull request merged**
