### PR TITLE
Homebrew install

### PR DESCRIPTION
**Pull request by jburel**
Review the installation on mac OS X
Indicate that this walkthrough is aimed at developers

Related PRs: 
 * https://github.com/ome/homebrew-alt/pull/120
 * https://github.com/ome/omero-install/pull/143

Looking at the developers section, I have not found a suitable place to insert that page into.

cc @hflynn

### CODE REVIEW

**Comment by jburel** [comment]
job is now green https://ci.openmicroscopy.org/job/OMERO-DEV-merge-homebrew/ICE=3.6,OSX=snapper/411/

**Comment by simleo** [comment]
Changes look good and render correctly. No reference to `omero52` left. Good to merge.

**Comment by hflynn** [comment]
Do you want to edit the entry about this page in the see also box at the top of https://www.openmicroscopy.org/site/support/omero5.3-staging/sysadmins/unix/server-installation.html as well?
You could also add a link to https://www.openmicroscopy.org/site/support/omero5.3-staging/developers/installation.html#building-omero if you liked, although that does already link to the installation overview page so it isn't really necessary.

**Comment by jburel** [comment]
For the second one, pointing at the overview page is better for now until we only have centos7 and ubuntu

**Comment by jburel** [comment]
@hflynn: updated server-installation

**Comment by hflynn** [comment]
Looks good thanks.

**Pull request merged**
