### PR TITLE
CLI output should not be highlighted.

### PR DESCRIPTION
**Pull request by mtbc**
Staged at https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-docs/lastSuccessfulBuild/artifact/omero/_build/html/sysadmins/cli/db.html. Compare with the previous at https://latest-ci.openmicroscopy.org/jenkins/job/OMERO-docs/lastSuccessfulBuild/artifact/omero/_build/html/sysadmins/cli/db.html.

### CODE REVIEW

**Comment by joshmoore** [comment]
I don't see a difference in Chrome.

**Comment by mtbc** [comment]
Perhaps the merge job had yet to run?

**Comment by joshmoore** [comment]
Perhaps (I assume staged == ready). Looks fine now. :+1:

**Comment by mtbc** [comment]
Sorry, when I write "staged" I usually mean "in good time for the stand-up wherein I list the PR"!

**Comment by jburel** [comment]
Merging for our last (hopefully) rc

**Pull request merged**
