### PR TITLE
Example for importing images

### PR DESCRIPTION
**Pull request by dominikl**
This PR adds an example for importing images to the Java examples for developers.

Based on @bramalingam 's  ICY plugin code: https://github.com/bramalingam/OmeroICY/blob/master/TestPlugin/src/plugins/bramalingam/OMEROICY/testOmero.java#L128

### CODE REVIEW

**Comment by hflynn** [comment]
Formats correctly on staging (https://www.openmicroscopy.org/site/support/omero5.2-staging/developers/Java.html) - I leave someone else to comment on the technical content.

**Comment by hflynn** [comment]
Is this fulfilling https://trello.com/c/yXt1nOAr/237-python-upload-example or would further additions be needed?

**Comment by joshmoore** [comment]
My primary thought looking at this is that for the general user this is more complicated than it needs to be, but code changes would be necessary to have something simpler/nicer.

**Comment by dominikl** [comment]
@joshmoore Instead of using OMEROMetadataStoreClient I could alternatively create an example using the gateway, in particular the TransferFacility: https://github.com/openmicroscopy/openmicroscopy/blob/develop/components/blitz/src/omero/gateway/facility/TransferFacility.java#L73 But that's still a bit experimental; this method is covered by an integration test, but it's actually not used by Insight yet (although I copied it from Insight's `OMEROGateway` ). Would that be better?

**Comment by joshmoore** [comment]
@dominikl : It might just be that we're in a transition phase. If `TransferFacility` is the new API, we could certainly work toward a production-grade example of that and then hide this example, or at least mark it as "low-level" or something.

**Comment by jburel** [comment]
@dominikl: I agree that we should push the usage of the gateway and make example using gateway
Time to have an "extended" minimal-omero-client
e.g. minimal viewer, minimal importer

**Comment by jburel** [comment]
Is the example run as part of training?

also I will be more explicit for the image imported or use fake.

**Comment by dominikl** [comment]
No, good point, forgot about that.

**Comment by dominikl** [comment]
Updated the doc to use the easier `LoginCredentials(String userName, ...)` respectively `LoginCredentials(String[] args0` constructor. As image placeholder `pathTo/image.dv` is used. I think that's actually quite clear, or should I really add the code for creating and using `.fake` image to the doc?

**Comment by jburel** [comment]
I will not use `fake` in the doc, better to use a "real" format

**Comment by jburel** [comment]
Thanks @dominikl

**Pull request merged**
