### PR TITLE
use sphinx_rtd_theme

### PR DESCRIPTION
**Pull request by jburel**
Set rtd theme

### CODE REVIEW

**Comment by sbesson** [comment]
This seems to fix the theme regression issue that has been observed between https://omero.readthedocs.io/en/v5.6.8-2/ and https://omero.readthedocs.io/en/v5.6.8-3/.

Is there an official link describing this as a the new canonical way to declare the RTD theme?
Will this be a change to apply across all rtd repositories (i.e. lots of upcoming noise)?

**Comment by jburel** [comment]
We will have to propagate across all repos. 
I have not seen a page
But RTD might have dropped it at some point because it did not have support for Sphinx 7 see https://github.com/readthedocs/sphinx_rtd_theme/issues/1463

The issue is now solved

**Review by sbesson — APPROVED** [review]
I believe the breaking change was introduced in https://docs.readthedocs.io/en/stable/changelog.html#version-10-2-0 and more specifically https://github.com/readthedocs/readthedocs.org/pull/10638

**Comment by jburel** [comment]
```
We are not installing sphinx-rtd-theme automatically on new projects. However, we are setting sphinx_rtd_theme automatically on their docs/conf.py.
```
This did not happen for us since we are using ``omero/conf.py`` (even if it is not a new project) so some of our repos will be okay

**Comment by snoopycrimecop** [comment]
Empty PR description. Please add a short summary of the PR scope and some testing instructions.

**Pull request merged**
