### PR TITLE
Use global replacements in autogen_docs sed commands

### PR DESCRIPTION
**Pull request by sbesson**
This should replace multiple instances of $WORKSPACE in the same line like
in the Apache configuration file.

### CODE REVIEW

**Comment by sbesson** [comment]
See https://github.com/snoopycrimecop/ome-documentation/commit/2e46dba1cdb3e0898ef7afbce85e85741e86471b for the application on this PR on top of #1307.

**Comment by mtbc** [comment]
The diff looks plausible.

**Comment by manics** [comment]
LGTM

**Comment by rleigh-dundee** [comment]
Looks fine to me also.

**Pull request merged**
