### PR TITLE
note 5.2-to-5.3m1 changes to model object glossary

### PR DESCRIPTION
**Pull request by mtbc**
This updates the model object glossary with the changes made so far in the ROIs/folders work.

### CODE REVIEW

**Comment by sbesson** [comment]
Barring the comment in the upstream PR, the diff looks good. It raises the question of whether we should start having an infrastructure (job, staging page) to review the `regions` PRs assuming we will start opening more.

**Comment by hflynn** [comment]
I think a merge build and staging location will be needed post 5.2.2 release yes. I have a bunch of things to do which I had planned to start on next week.

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-REGIONS-merge-docs#2](https://ci.openmicroscopy.org/job/OMERO-REGIONS-merge-docs/2/). See the [console output](https://ci.openmicroscopy.org/job/OMERO-REGIONS-merge-docs/2/consoleText) for more details.
Possible conflicts:
- Conflict detection failed
  - None

**Comment by sbesson** [comment]
Staged at http://www.openmicroscopy.org/site/support/omero5.3-staging/developers/Model/EveryObject.html

**Pull request merged**
