### PR TITLE
do not show settings.env header comment on walkthrough page

### PR DESCRIPTION
**Pull request by mtbc**
Omits the header comment introduced by https://github.com/ome/omero-install/pull/35 from the literal include on http://www.openmicroscopy.org/site/support/omero5.1-staging/sysadmins/unix/server-linux-walkthrough.html.

### CODE REVIEW

**Comment by sbesson** [comment]
This file is actually a copy of https://github.com/ome/omero-install/blob/master/linux/settings.env. Want to open a PR against the upstream repo?

**Comment by mtbc** [comment]
Thank you, now adjusted this PR accordingly.

**Comment by hflynn** [comment]
Travis doesn't like this

**Comment by mtbc** [comment]
Let's see if it needs a manual copy of that file from the other repository.

**Pull request merged**
