### PR TITLE
Cap table to 3.9

### PR DESCRIPTION
**Pull request by jburel**
Cap tables installations

### CODE REVIEW

**Review by sbesson — CHANGES_REQUESTED** [review]
See https://github.com/PyTables/PyTables/releases/tag/v3.9.1 looks like Pytables has officially dropped support for Python 3.8  in the 3.9.x line so I think we can use this semantics in the documentation.

**Review by sbesson — CHANGES_REQUESTED** [review]
As per https://github.com/PyTables/PyTables/issues/1062#issuecomment-1752482749 and the yanking of PyTables 3.9.0 combined with the correct metadata requirements in PyTables 3.9.1, it feels like there is no more need to have specific capping instructions either in the developer documentation or in the troubleshotting and `pip install tables` should install the latest supported PyTables version on any Python 3.8+ environment.

**Comment by jburel** [comment]
@sbesson I have now removed the cap and only indicated the Python supported version

**Review by sbesson — APPROVED** [review]
:+1: The intent is to raise the minimal supported version of Python to 3.8 anyways right?

**Comment by jburel** [comment]
It is yes.

**Pull request merged**
