### PR TITLE
Gateway

### PR DESCRIPTION
**Pull request by jburel**
First round of review of the gateway usage

### CODE REVIEW

**Comment by dominikl** [comment]
Looks good!

**Comment by jburel** [comment]
@dominikl: anything you think we should simplify.
As indicated  I have started a list of code improvement for 5.2.1 (on paper only!!)

**Comment by dominikl** [comment]
I think the examples are as simple as it's possible with the current Gateway.

**Comment by dominikl** [comment]
For the further Gateway improvement, I think there should definitely be easier methods for annotating objects and uploading/importing (which deal with all the object linking tasks automatically).

**Comment by sbesson** [comment]
Merging.

**Comment by hflynn** [comment]
Does this complete the item on https://trello.com/c/2Mzfzvho/74-developer-doc-updates or are you planning another PR before the release for gateway stuff?

**Comment by jburel** [comment]
@hflynn: I might have another PR. I am currently working on https://github.com/jburel/minimal-omero-client to use the gateway

**Comment by hflynn** [comment]
Ah ok, will leave you to cross the task off when you're done then, thanks.

**Pull request merged**
