### PR TITLE
Document minor schema release

### PR DESCRIPTION
**Pull request by hflynn**
As documented on the BF docs https://www.openmicroscopy.org/site/support/bio-formats5.2/about/whats-new.html#october-5 Bio-Formats 5.2.3 contained a minor schema release. This PR updates the schema history docs in the Model & Formats Documentation to reflect this.

Staged at https://www.openmicroscopy.org/site/support/ome-model-staging/schemas/october-2016.html

### CODE REVIEW

**Comment by rleigh-codelibre** [comment]
There is no "October 2016" schema, so should this not simply be added to the end of the June 2016 page as an addendum containing just the changes at the bottom?  A separate page for what is essentially exactly the same schema seems a bit confusing.

If it is retained as a separate page:
- It doesn't explicitly state that it's a minor update to the 2016-06 schema.  There's a note about it using the "same namespace" but this is too vague.
- "File writers will not necessarily need corrected."  They won't need any changes _at all_, so I don't think this is even worth mentioning.

**Comment by hflynn** [comment]
I followed the pattern of the existing docs - September 2007 is a minor release with a separate page. I'll amend the intro text I copied to be more specific, thanks.

**Comment by rleigh-codelibre** [comment]
Was what we did in the past correct though?  There isn't an October 2016 release.  We might have made the 2016-06 update _in_ October, but that's an irrelevance when it comes to the actual schema versioning.  It's 2016-06 release 2.

**Comment by hflynn** [comment]
The title is 'Changes for October 2016' not 'October 2016 release' but it is confusing given all the rest of them bar Sept 2007 are changes AND release version. I'll amend the file names & titles too.

**Comment by hflynn** [comment]
Hopefully that's better @rleigh-codelibre - you can blame @sbesson for the orphaned Sept 2007 file, he didn't want me to break the URL ;)

**Comment by hflynn** [comment]
http://www.openmicroscopy.org/site/support/ome-model-staging/#data-model-history rebuilt

**Comment by rleigh-codelibre** [comment]
The updated version looks fine, thanks.  One trivial whitespace issue noted.

**Comment by hflynn** [comment]
Thanks @rleigh-codelibre I'll remove that extra whitespace at the end of the pages before I merge.

**Pull request merged**
