### PR TITLE
Update omerodocs.py for Sphinx 1.7

### PR DESCRIPTION
**Pull request by hflynn**
See https://trello.com/c/uyNZDHhJ/47-sphinx-170

This builds fine with my local version of Sphinx 1.6.3 so should be backwards compatible that far at least.

Used for the config glossary /sysadmins/config.html

### CODE REVIEW

**Comment by sbesson** [comment]
From my side, assuming this also builds correctly on the CI infrastructure, no objection to getting this in to be forward-compatible with Sphinx 1.7. /cc @dominikl @jburel

**Comment by hflynn** [comment]
https://ci.openmicroscopy.org/view/Docs/job/OMERO-DEV-merge-docs/1022/ is green with this included and the properties links still work and the glossary page renders as expected - I'm not seeing any difference to before the change

**Comment by dominikl** [comment]
👍

**Comment by jburel** [comment]
no objections now that CI is green

**Pull request merged**
