### PR TITLE
NOT TO BE MERGED walkthroughs

### PR DESCRIPTION
**Pull request by jburel**
Update manually the walkthroughs
This PR is solely to help the review of 
* https://github.com/ome/omeroweb-install/pull/39
* https://github.com/ome/omeroweb-install/pull/38
* https://github.com/ome/omero-install/pull/174

### CODE REVIEW

**Comment by rgozim** [comment]
Page being reviewed: `html/sysadmins/unix/server-ubuntu-ice36.html`

Under title _Installing prerequisites_ there is a bit of repetition of installation of certain prerequisites, `unzip` and `wget`. Doesn't really make a difference, just a bit cleaner. 

Also some inconsistency with the `apt-get -y install`. Under the `# install dependencies` comment, being split across multiple lines doesn't work with copy paste. The rest of page keeps all installs on a single line. 

screen shot 2018-02-09 at 17 53 46

screen shot 2018-02-09 at 17 50 18

**Comment by rgozim** [comment]
Page being reviewed: **html/sysadmins/unix/server-ubuntu-ice36.html**

I think there is an error with the documentation flow for Ubuntu. As a developer, you are directed to the page **_server-ubuntu-ice36.html_** in order to obtain the prerequisites for OMERO Server. Under the section section **_"To install Ice 3.6:"_** there is a line `pip install "zeroc-ice>3.5,<3.7"`. This will install a particular Ice version to the developers _global_ pip packages, which is not inline with what we recommend by using a Virtualenv environment.

screen shot 2018-02-13 at 09 57 29

**Comment by jburel** [comment]
The virtalenv is for web installation if this is what you are indicating

Edit: this is for omego download.
We could it to convenience package like zip

**Comment by jburel** [comment]
Looking at your screenshot we can probably also remove ``zeroc-ice-all-dev``

**Comment by rgozim** [comment]
Does that then mean we do not need the `pip install "zeroc-ice>3.5,<3.7"` for Server prerequisites installation?

**Comment by jburel** [comment]
you need to have it installed

**Comment by rgozim** [comment]
I think if you remove `zeroc-ice-all-dev` there will be issues for developers trying to build OMERO Server from source. Developers are pointed to the same requirements page as sysadmins.

See: https://docs.openmicroscopy.org/omero/5.4.0/developers/installation.html#building-omero

**Comment by jburel** [comment]
Migrating "pip install in virtualenv`` will require a bit more work
Outside the scope of 5.4.4, I could certainly tackle that afterwards

**Comment by rgozim** [comment]
Found an issue with the database creation part of the Ubuntu doc (server-ubuntu-ice36.html)

At the end of _Installing prerequisites_ executing `psql -P pager=off -h localhost -U "$OMERO_DB_USER" -l` in a terminal fails with:
```
psql: FATAL:  password authentication failed for user "db_user"
FATAL:  password authentication failed for user "db_user"
```
Calling `psql` in terminal results in `FATAL:  role "rgozim" does not exist`, which means the current user has not been added to the database. We should maybe add something like this to the Postgres installation section https://stackoverflow.com/a/32376533/272446

**Comment by jburel** [comment]
You will have to show me what are your settings

**Comment by rgozim** [comment]
Requirements documentation are working fine for Ubuntu with `APT::Install-Recommends "false"; APT::Install-Suggests "false";`  👍

**Pull request closed without merging**
