### PR TITLE
Remove bin/omero

### PR DESCRIPTION
**Pull request by jburel**
Replace ``bin/omero`` -> ``omero``

### CODE REVIEW

**Review by manics — COMMENTED** [review]
`git grep -n bin/omero`

May be relevant:
```
common/conf.py:34:    # bin/omero db upgrade
omero/developers/cli/index.rst:19:-  Any command can be produced by symlinking :file:`bin/omero` to a file of
omero/sysadmins/grid.rst:434:Shortcuts allow the :file:`bin/omero` script to function as an init.d script
omero/sysadmins/grid.rst:446:The same works for putting :file:`bin/omero` on your path:
omero/sysadmins/in-place-import.rst:59:* an |OS|-account with access to :file:`bin/omero`
omero/sysadmins/omero-home-prefix.rst:28:as detected by the `bin/omero` family of utilities.
omero/sysadmins/search.rst:164:   $ JAVA_OPTS="-Domero.search.max_partition_size=100000" bin/omero admin reindex --foreground
```
Unrelated issue, there are double `//` in these paths:
```
omero/sysadmins/unix/install-web/walkthrough/omeroweb-install-debian9-ice3.6.rst:194:    OMERO=/opt/omero/web//bin/omero
omero/sysadmins/unix/install-web/walkthrough/omeroweb-install-ubuntu1604-ice3.6.rst:191:    OMERO=/opt/omero/web//bin/omero
omero/sysadmins/unix/install-web/walkthrough/omeroweb-install-ubuntu1804-ice3.6.rst:190:    OMERO=/opt/omero/web//bin/omero
```

**Comment by jburel** [comment]
The double ``//`` indicates that something is not correct in omeroweb-install

edit: problem in autogen. I will fix it in another PR

**Comment by jburel** [comment]
Double ``//`` in the path is fixed in https://github.com/ome/ome-documentation/pull/2069
To check output download zip from https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-docs-superbuild-build/52/

**Comment by will-moore** [comment]
Changes look good. 👍

**Pull request merged**
