### PR TITLE
link to omero-py API doc

### PR DESCRIPTION
**Pull request by jburel**
Add link to omero-py API doc

### CODE REVIEW

**Comment by will-moore** [comment]
`https://omero-py.readthedocs.io/` won't create a clickable link, right? That would be nice.

**Comment by jburel** [comment]
The link is clickable see https://omero--2283.org.readthedocs.build/en/2283/developers/Python.html

**Comment by joshmoore** [comment]
image

**Comment by jburel** [comment]
@will-moore any other comment?

**Review by will-moore — APPROVED** [review]
LGTM 👍

**Pull request merged**
