### PR TITLE
Fix link to util/populate_roi.py

### PR DESCRIPTION
**Pull request by will-moore**
Fix build failure:
```
- 404 Client Error: Not Found for url: https://github.com/ome/openmicroscopy/blob/develop/components/tools/OmeroPy/src/omero/util/populate_roi.py
```

### CODE REVIEW

**Comment by mtbc** [comment]
Maybe these repos need adding into `omero/conf.py`'s `omero_extlinks`.

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#181](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-docs/181/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-docs/181/consoleText) for more details.
Possible conflicts:
  - PR #2015 will-moore 'web app docker template'
    - omero/developers/Web/CreateApp.rst

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-docs#183](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-docs/183/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-docs/183/consoleText) for more details.
Possible conflicts:
  - PR #2015 will-moore 'web app docker template'
    - omero/developers/testing.rst

~~--conflicts~~ Conflict resolved in build [OMERO-docs#78](https://idr-ci.openmicroscopy.org/jenkins/job/OMERO-docs/78/). See the [console output](https://idr-ci.openmicroscopy.org/jenkins/job/OMERO-docs/78/consoleText) for more details.

**Comment by will-moore** [comment]
The OMERO-docs job is green again: https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-docs/184/

**Comment by sbesson** [comment]
Generally looks good. Any thoughts about @mtbc's suggestion in https://github.com/ome/ome-documentation/pull/2020#issuecomment-530393138 to define new `web_source` and `py_source` extlinks in https://github.com/ome/ome-documentation/blob/develop/omero/conf.py#L99?

**Comment by will-moore** [comment]
I'm not sure how ```web_source``` and ```py_source``` extlinks would help us.
I usually find that I need to browse to the source anyway, to check I have the link right. Then it's easier for me to put that in a regular link than to remember or find an example of how to use extlinks. So I don't find that they make docs writing any easier. Do they help us in any other way (back-links etc)?

**Comment by sbesson** [comment]
@will-moore using extlinks is the strategy that had been decided collectively during the OMERO 5.5 work. Understood that it would constitutes an extra simplification step in the workflow you describe above although we are talking of an overhead of a few seconds.

The primary benefit is the management of the component versions since the extlinks point at tags of the source code. As components get released rapidly, this allows us to keep the entire documentation in sync by updating a single file rather than reviewing all pages - see https://github.com/ome/ome-documentation/pull/2003 for an example.

**Review by sbesson — APPROVED** [review]

**Pull request merged**
