### PR TITLE
Auto update

### PR DESCRIPTION
**Pull request by jburel**
This PR replaces https://github.com/ome/omero-documentation/pull/2258
I deleted my fork inadvertently leading to the closure of the original PR
In this PR, I have 
* split the original script into ``autogen_omero_install``, ``autogen_omero_webinstall``, ``autogen_openmicroscopy``, ``autogen_dependencies``
* used ``ome/openmicroscopy`` HEAD to generate the doc for configuration and history.
* used ``ome/openmicroscopy`` Latest release to determine the dependencies version
* used ``omero-web`` release version for configuration
* generated model object documentation using ``ome/openmicroscopy`` HEAD
* reduced the number of dependencies in the virtual env.

a bash script is used to determine the dependencies,  this approach fits with the existing set up and it feels more "natural" considering the commands used. A python script was introduced in 2015 by Simon to determine the DB version. 
Using CLI python will require some potential change in omero-py itself to extend some of parsing e.g. https://github.com/ome/omero-py/blob/master/src/omero/cli.py#L104
The python script was introduced for convenience, I think, at the time.

Those scripts are meant to be used in a CI context, they can be used locally as long as it mimics the expected set up e.g. omero-install needs to be checked out, ``OMERO.server`` <-> ``openmicroscopy`` symlink

To test the new script ``autogen_dependencies``:
* modify ``version_openmicroscopy = "5.6.5"`` to ``version_openmicroscopy = "5.6.4"`` for example
* run ``bash omero/autogen_dependencies.sh``
* check the autoput i.e. ``echo package +version``

### CODE REVIEW

**Comment by will-moore** [comment]
Don't understand most of what the script is doing I'm afraid, but it's doing something (with `version_openmicroscopy = "5.6.4"`):
```
$ bash omero/autogen_dependencies.sh
dsl_plugin
5.5.2
blitz_plugin
5.5.2
5.6.5
blitz.jar
5.5.12
server.jar
5.6.4
gateway.jar
5.6.10
romio.jar
5.7.0
renderer.jar
5.5.10
common.jar
5.5.10
model.jar
5.6.7
formats-gpl.jar
6.10.0
```

**Comment by jburel** [comment]
The script checks the latest version of the published packages (java, python, etc.). If a new version is detected it upgrades the version in ``auto_conf.py``.
When 5.6.4 openmicroscopy is set in the file, it notices that 5.6.5 is available and then scan the dependencies and find the version and upgrade ``auto_conf.py`` if required

I will add more doc to the script

**Comment by dominikl** [comment]
I was wondering too. Changed to `5.6.4` and suddenly it's `5.6.5` again. Quite hard to understand what's happening, but as long as it works. Tried to run the whole thing locally `autogen_omero.sh`, but it tries to install ice and fails to compile, probably an issue specific to OSX.

**Comment by jburel** [comment]
The whole things requires a bigger set-up. That's already in place. 
The dependencies update is what has been added. 
the other commits are related to the split of the original script.

**Comment by dominikl** [comment]
👍 Looks good to me.

**Comment by jburel** [comment]
Merging so we can test the workflow with an insight release

**Comment by sbesson** [comment]
While working on https://github.com/ome/omero-documentation/pull/2268, I was initially deceived by the build logs which raise errors due to the removal of a variable in this PR

````
01:14:18 /home/omero/workspace/OMERO-docs/omero/developers/Server/Permissions.rst:5: ERROR: Undefined substitution referenced: "version_omero_server".
01:14:18 /home/omero/workspace/OMERO-docs/omero/developers/Server/Permissions.rst:10: ERROR: Undefined substitution referenced: "version_omero_server".
01:14:18 /home/omero/workspace/OMERO-docs/omero/developers/Server/Permissions.rst:411: ERROR: Undefined substitution referenced: "version_omero_server".
01:14:18 /home/omero/workspace/OMERO-docs/omero/index.rst:5: ERROR: Undefined substitution referenced: "version_omero_server".
01:14:18 /home/omero/workspace/OMERO-docs/omero/index.rst:39: ERROR: Undefined substitution referenced: "version_omero_server".
01:14:18 /home/omero/workspace/OMERO-docs/omero/index.rst:44: ERROR: Undefined substitution referenced: "version_omero_server".
01:14:18 /home/omero/workspace/OMERO-docs/omero/sysadmins/UpgradeCheck.rst:29: ERROR: Undefined substitution referenced: "version_omero_server".
01:14:18 /home/omero/workspace/OMERO-docs/omero/sysadmins/omeroweb-upgrade.rst:10: ERROR: Undefined substitution referenced: "version_omero_server".
01:14:18 /home/omero/workspace/OMERO-docs/omero/sysadmins/server-upgrade.rst:10: ERROR: Undefined substitution referenced: "version_omero_server".
01:14:18 /home/omero/workspace/OMERO-docs/omero/sysadmins/server-upgrade.rst:174: ERROR: Undefined substitution referenced: "version_omero_server".
01:14:18 /home/omero/workspace/OMERO-docs/omero/sysadmins/server-upgrade.rst:300: ERROR: Undefined substitution referenced: "version_omero_server".
01:14:18 /home/omero/workspace/OMERO-docs/omero/sysadmins/unix/server-installation.rst:274: ERROR: Undefined substitution referenced: "version_omero_server".
01:14:18 /home/omero/workspace/OMERO-docs/omero/sysadmins/unix/server-installation.rst:302: ERROR: Undefined substitution referenced: "version_omero_server".
01:14:18 /home/omero/workspace/OMERO-docs/omero/sysadmins/unix/server-installation.rst:641: ERROR: Undefined substitution referenced: "version_omero_server".
````

Should these be updated to `version_openmicroscopy` or are we maintaining  both aliases moving forward?

Update: this was separately captured as https://github.com/ome/omero-documentation/issues/2267

**Comment by jburel** [comment]
Thanks for spotting that and for capturing it. The name should have been updated

**Pull request merged**
