### PR TITLE
CentOS6 selinux policy changes are needed for Apache as well as Nginx

### PR DESCRIPTION
**Pull request by manics**
Update walkthrough to include Selinux configuration for Apache as well as Nginx. Corresponds to changes made in https://github.com/ome/omero-install/pull/24 (including a file name change).

--depends-on ome/omero-install#24

### CODE REVIEW

**Comment by sbesson** [comment]
See https://ci.openmicroscopy.org/job/OMERO-5.1-merge-docs-autogen/. This PR broke the auto-generation job because at the moment we do not have any logic in place to handle ome-documentation/omero-install dependencies.
Should we let snoopy fork of ome/omero-install, do a merge build and use this branch fro the job above?

**Comment by sbesson** [comment]
Branch pushed manually. Changes are staged at https://www.openmicroscopy.org/site/support/omero5.1-staging/sysadmins/unix/server-linux-walkthrough.html

**Comment by manics** [comment]
Sorry, I should've realised. If it only happens occasionally then waiting for the first PR to be merged before opening the second would work.

**Comment by sbesson** [comment]
Agreed. Especially for documentation purposes, the code usually needs to be reviewed first. Once this is in. I will switch the `merge-docs-autogen` job back to `origin/master`

**Comment by rleigh-dundee** [comment]
Changes look fine; please merge.

**Comment by manics** [comment]
I'll rebase at some point but it's a bit more complicated.

--no-rebase to silence the job

**Pull request merged**
