### PR TITLE
Django redis

### PR DESCRIPTION
**Pull request by jburel**
Cap version and manually update walkthrough

### CODE REVIEW

**Comment by hflynn** [comment]
this looks fine and catching all the redis mentions I find by grepping - just re-running the docs build to confirm everything is good to go

**Comment by hflynn** [comment]
Merge build is green and the install-web page looks fine. Where is the script used? I'm not finding where it's included in the docs by grepping

**Comment by jburel** [comment]
It used to be used http://docs.openmicroscopy.org/omero/5.4.3/sysadmins/unix/server-install-homebrew.html but it seems that is no longer needed
probably something to clean next time
 @rgozim changed that page so we can probably get rid of the walkthrough

**Comment by hflynn** [comment]
👍 good to merge then, we can clean up unused scripts after the release

**Comment by hflynn** [comment]
I'll leave you to merge this with the install PR assuming that is cleared later @jburel

**Comment by jburel** [comment]
Thanks @hflynn 
code PR has been merged

**Pull request merged**
