### PR TITLE
update 5.1 patch version to 1

### PR DESCRIPTION
**Pull request by mtbc**
Have the documentation show the correct patch version for the 5.1 release.

This is rather unfortunate, and should perhaps be reverted for 5.2.

--no-rebase

### CODE REVIEW

**Comment by manics** [comment]
If it'll make maintenance easier you could add a `dbpatch` variable to `omero/conf.py`

**Comment by hflynn** [comment]
That sounds like a good idea

**Comment by mtbc** [comment]
Reading `omero/conf.py` I realize I don't know how to do that. (Presumably we need both `previousdbpatch` and `dbpatch`.) Would you be able to alter it, then I'll adjust the actual documentation pages?

**Comment by hflynn** [comment]
Would we need previous as well? I'd assume just add `dbpatch` so you only have to update it in the config if it changes. @manics are you going to try this out or shall I?

**Comment by manics** [comment]
New proposal.... just get rid of those args https://trello.com/c/8PPlaBmP/456-remove-compulsory-version-patch-args-from-db-script

**Comment by mtbc** [comment]
For things like,
```
$ psql -h localhost -U **db_user** **omero_database** < sql/psql/OMERO\ |version|\_\_1/OMERO\ |previousversion|\_\_0.sql
```
this time there will still be a 0 with the previous version, but for version=5.2 it will be a 1 with previousversion=5.1.

**Comment by manics** [comment]
Note `omero db script` output has now changed: https://github.com/openmicroscopy/openmicroscopy/pull/3615

**Comment by hflynn** [comment]
@mtbc can you update this PR to reflect the changes above please?

**Comment by mtbc** [comment]
Do we have the `conf.py` changes yet?

**Comment by hflynn** [comment]
Maybe I misunderstood, i thought @manics had removed the need for the version change

**Comment by mtbc** [comment]
We still need it for the part where one runs the SQL upgrade script.

**Comment by manics** [comment]
I'm working on the web docs at the moment, after that I'll attempt to make the conf change here if no-one else gets to it first.

**Comment by mtbc** [comment]
Now apparently will need to adjust `sysadmins/cli/db.txt`.

**Comment by mtbc** [comment]
@manics will take all this over once his `conf.py` changes are ready to go.

**Pull request closed without merging**
