### PR TITLE
Flim clean up

### PR DESCRIPTION
**Pull request by jburel**
Remove ref to scripts that no longer exist in the repo.

Corresponding PR https://github.com/openmicroscopy/openmicroscopy/pull/4650

### CODE REVIEW

**Comment by mtbc** [comment]
Not sure why we don't mention `Dataset_To_Plate.py` nor `Populate_Metadata.py` nor any of the analysis scripts but I'm happy for this to be **merged** as an improvement.

**Comment by hflynn** [comment]
Holding off for now as it's not clear to me what's happening on the code front

**Comment by jburel** [comment]
@hflynn: The files listed in the doc no longer exist in the scripts repo, and have not been for a while. Not directly related to the code clean up PR.

@mtbc: it is a partial view of what is currently listed in the DB.

**Comment by hflynn** [comment]
Thanks for the clarification, merging.

**Pull request merged**
