### PR TITLE
Use https for redirecting links

### PR DESCRIPTION
**Pull request by hflynn**
https://ci.openmicroscopy.org/view/Docs/job/OMERO-DEV-merge-docs/ was complaining about this link, probably temporarily but it is redirecting to https anyway so maybe this will help.

### CODE REVIEW

**Comment by hflynn** [comment]
https://ci.openmicroscopy.org/view/Docs/job/OMERO-DEV-merge-docs/971/console is still read because http://trac.nginx.org/nginx/roadmap  is being slow to load and timing out but at least it isn't complaining about this link any more

**Comment by hflynn** [comment]
https://ci.openmicroscopy.org/view/Docs/job/OMERO-DEV-merge-docs/973/ is finally green now

**Comment by rleigh-codelibre** [comment]
All looks fine to merge to me.

**Comment by hflynn** [comment]
Latest build is green today so I'll try taking the nginx link off the ignore list again before I merge this.

**Comment by hflynn** [comment]
https://ci.openmicroscopy.org/view/Docs/job/OMERO-DEV-merge-docs/975/ is still green with the link no-longer ignored, merging.

**Pull request merged**
