### PR TITLE
Update link

### PR DESCRIPTION
**Pull request by jburel**
Update link to point to a more suitable page.

cc @rleigh-dundee

### CODE REVIEW

**Comment by hflynn** [comment]
That page doesn't mention Django, does it still need adding to the server installation pages?

**Comment by hflynn** [comment]
Does help if I check the right staging pages! Looks good, thanks.

**Comment by hflynn** [comment]
Will let @rleigh-dundee reply before I merge but this works for me.

**Comment by rleigh-dundee** [comment]
@hflynn It's already documented on the server installation page, so it's all fine with me.

**Pull request merged**
