### PR TITLE
omero: Finalise minimum version requirements

### PR DESCRIPTION
**Pull request by rleigh-dundee**
Remove "proposal" from the changes.

### CODE REVIEW

**Comment by hflynn** [comment]
while you are changing this page anyway - the anchor link for http://support.microsoft.com/gp/lifeselectindex#W is upsetting the build and it doesn't work for me on Safari or Chrome - can you take it out and indicate people should click on 'W' in the link text instead please?

**Comment by hflynn** [comment]
Thanks!

**Comment by hflynn** [comment]
Intention is to review and merge this in time to have it in the live docs for m4 so that Roger can email the link to people without needing to refer them to the staging pages.
Further alterations can always be done in a follow on PR.

**Comment by hflynn** [comment]
This reads and renders fine, I'm happy to merge tomorrow morning unless anyone has any objections.

**Comment by rleigh-dundee** [comment]
--no-rebase

**Pull request merged**
