### PR TITLE
Copy missing files

### PR DESCRIPTION
**Pull request by jburel**
Copy the setup files
Reported in the following post https://www.openmicroscopy.org/community/viewtopic.php?t=8163&p=17699#p17699

### CODE REVIEW

**Comment by hflynn** [comment]
I take it this needs the autogen build to run to copy the extra content across?

**Comment by jburel** [comment]
it will but I still have one thing to do on the omero-install front before we do the autogen

**Comment by hflynn** [comment]
Ah ok, thanks for the clarification.

**Comment by jburel** [comment]
Related omero-install PR https://github.com/ome/omero-install/pull/126

**Comment by jburel** [comment]
Since we do not have a job anymore and cannot adjust the develop one w/o resurrecting a number of other jobs, I will open a PR manually copying the missing file and updating the walkthrough

**Comment by jburel** [comment]
--rebased-to #1585

**Comment by jburel** [comment]
Closing this PR since the copy will happen manually

**Pull request closed without merging**
