### PR TITLE
remove misleading regex metacharacters from linkcheck_ignore

### PR DESCRIPTION
**Pull request by mtbc**
Removing the leading `^` so as not to give the impression that partial string matches could work. `linkcheck_ignore` does whole-string matching so this PR should not change any behavior.

### CODE REVIEW

**Comment by hflynn** [comment]
Is there anything to test here aside from builds being green?

**Comment by hflynn** [comment]
https://ci.openmicroscopy.org/view/Docs/job/OMERO-DEV-merge-docs/311/ green with this included

**Comment by hflynn** [comment]
https://ci.openmicroscopy.org/view/Docs/job/CONTRIBUTING-merge-docs/746/ also green

**Comment by mtbc** [comment]
Thank you.

**Pull request merged**
