### PR TITLE
Update auto-generated properties

### PR DESCRIPTION
**Pull request by snoopycrimecop**
Repository: openmicroscopy/ome-documentation
Already up-to-date.

Generated by build [OMERO-5.1-latest-docs-autogen#340](http://ci.openmicroscopy.org/job/OMERO-5.1-latest-docs-autogen/340/).

----
--no-rebase

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#715](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/715/). See the [console output](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/715/consoleText) for more details.
Possible conflicts:
  - PR #1069 manics 'Web-server config generation'
    - omero/sysadmins/unix/apache-fcgi-omero.conf
    - omero/sysadmins/unix/apache-omero.conf
    - omero/sysadmins/unix/nginx-omero.conf

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-5.1-merge-docs#372](http://ci.openmicroscopy.org/job/OMERO-5.1-merge-docs/372/). See the [console output](http://ci.openmicroscopy.org/job/OMERO-5.1-merge-docs/372/consoleText) for more details.
Possible conflicts:
  - PR #1069 manics 'Web-server config generation'
    - omero/sysadmins/unix/apache-fcgi-omero.conf
    - omero/sysadmins/unix/apache-omero.conf
    - omero/sysadmins/unix/nginx-omero.conf

**Comment by manics** [comment]
Comparing changes against #1069: `git cherry-pick 7ee85bb -X theirs`
```
diff --git a/omero/sysadmins/unix/apache-fcgi-omero.conf b/omero/sysadmins/unix/apache-fcgi-omero.conf
index 22db50b..75cbc88 100644
--- a/omero/sysadmins/unix/apache-fcgi-omero.conf
+++ b/omero/sysadmins/unix/apache-fcgi-omero.conf
@@ -6,7 +6,7 @@
 #  OmeroForceSSL - redirect all http requests to https
 
 ###
-### Example SSL stanza for OMERO.web created 2015-01-15 16:29:14.673131
+### Example SSL stanza for OMERO.web created 2015-01-22 10:11:25.546005
 ###
 
 # Eliminate overlap warnings with the default ssl vhost
@@ -51,15 +51,15 @@
 RewriteEngine on
 
 ###
-### Stanza for OMERO.web created 2015-01-15 16:29:14.673131
+### Stanza for OMERO.web created 2015-01-22 10:11:25.546005
 ###
 
-<Directory "/home/omero/OMERO.server/var">
+<Directory "/opt/hudson/workspace/OMERO-5.1-latest-docs-autogen/OMERO.server/var">
     Options -Indexes +FollowSymLinks
     Require all granted
 </Directory>
 
-<Directory "/home/omero/OMERO.server/lib/python/omeroweb/static">
+<Directory "/opt/hudson/workspace/OMERO-5.1-latest-docs-autogen/OMERO.server/lib/python/omeroweb/static">
     Options -Indexes +FollowSymLinks
     Require all granted
 </Directory>
@@ -68,7 +68,7 @@ RewriteEngine on
     Require all granted
 </Location>
 
-Alias /static /home/omero/OMERO.server/lib/python/omeroweb/static
+Alias /static /opt/hudson/workspace/OMERO-5.1-latest-docs-autogen/OMERO.server/lib/python/omeroweb/static
 
 RewriteCond %{REQUEST_URI} !^(/static|/\.fcgi)
 RewriteRule ^(/|$)(.*) /.fcgi/$2 [PT]
diff --git a/omero/sysadmins/unix/apache-omero.conf b/omero/sysadmins/unix/apache-omero.conf
index 98ead61..0da3997 100644
--- a/omero/sysadmins/unix/apache-omero.conf
+++ b/omero/sysadmins/unix/apache-omero.conf
@@ -8,7 +8,7 @@
 #  OmeroForceSSL - redirect all http requests to https
 
 ###
-### Example SSL stanza for OMERO.web created 2015-01-15 16:29:12.377728
+### Example SSL stanza for OMERO.web created 2015-01-22 10:11:23.263666
 ###
 
 # Eliminate overlap warnings with the default ssl vhost
@@ -53,21 +53,21 @@
 
 
 ###
-### Stanza for OMERO.web created 2015-01-15 16:29:12.377728
+### Stanza for OMERO.web created 2015-01-22 10:11:23.263666
 ###
-FastCGIExternalServer "/home/omero/OMERO.server/var/omero.fcgi" -host 0.0.0.0:4080 -idle-timeout 60
+FastCGIExternalServer "/opt/hudson/workspace/OMERO-5.1-latest-docs-autogen/OMERO.server/var/omero.fcgi" -host 0.0.0.0:4080 -idle-timeout 60
 
-<Directory "/home/omero/OMERO.server/var">
+<Directory "/opt/hudson/workspace/OMERO-5.1-latest-docs-autogen/OMERO.server/var">
     Options -Indexes FollowSymLinks
     Order allow,deny
     Allow from all
 </Directory>
 
-<Directory "/home/omero/OMERO.server/lib/python/omeroweb/static">
+<Directory "/opt/hudson/workspace/OMERO-5.1-latest-docs-autogen/OMERO.server/lib/python/omeroweb/static">
     Options -Indexes FollowSymLinks
     Order allow,deny
     Allow from all
 </Directory>
 
-Alias /static /home/omero/OMERO.server/lib/python/omeroweb/static
-Alias / "/home/omero/OMERO.server/var/omero.fcgi/"
+Alias /static /opt/hudson/workspace/OMERO-5.1-latest-docs-autogen/OMERO.server/lib/python/omeroweb/static
+Alias / "/opt/hudson/workspace/OMERO-5.1-latest-docs-autogen/OMERO.server/var/omero.fcgi/"
diff --git a/omero/sysadmins/unix/nginx-omero.conf b/omero/sysadmins/unix/nginx-omero.conf
index 9d5bd7f..06deae5 100644
--- a/omero/sysadmins/unix/nginx-omero.conf
+++ b/omero/sysadmins/unix/nginx-omero.conf
@@ -5,13 +5,13 @@
 
         # maintenance page serve from here
         location @maintenance {
-            root /home/omero/OMERO.server/etc/templates/error;
+            root /opt/hudson/workspace/OMERO-5.1-latest-docs-autogen/OMERO.server/etc/templates/error;
             try_files $uri $uri/ /502.html =502;
         }
 
         # weblitz django apps serve media from here
         location /static {
-            alias /home/omero/OMERO.server/lib/python/omeroweb/static;
+            alias /opt/hudson/workspace/OMERO-5.1-latest-docs-autogen/OMERO.server/lib/python/omeroweb/static;
         }
 
         location / {
```

* Timestamps might be an issue (can we ignore them unless there's an actual change?)
* Directories are prefixed with the Jenkins job workspace

**Comment by sbesson** [comment]
Auto-generated doc  PRs are usually only updated for releases. Bumping timestamps on this occasion does not bother me to much since we effectively regenerate these configuration files  /cc @hflynn 

Re directories, is `/home/omero` the default path for UNIX installation guide?. A possiblity would be to set-up the CI node to symlink the server in this folder and then call

```
/home/omero/OMERO.server/bin/omero web config...
```

**Comment by manics** [comment]
It's assumed the system user is `omero`: http://www.openmicroscopy.org/site/support/omero5/sysadmins/unix/server-linux-walkthrough.html

I don't think it matters what the prefix is, as long as it's reasonably short.

**Comment by hflynn** [comment]
Yeah, I think timestamps thing is fine in this case.

**Comment by sbesson** [comment]
Job configuration updated to run `sed "s|$WORKSAPCE|/home/omero|" ` on the generated config file. Only question remaining are the timestamps.

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-5.1-merge-docs#373](http://ci.openmicroscopy.org/job/OMERO-5.1-merge-docs/373/). See the [console output](http://ci.openmicroscopy.org/job/OMERO-5.1-merge-docs/373/consoleText) for more details.
Possible conflicts:
  - PR #1069 manics 'Web-server config generation'
    - omero/sysadmins/unix/apache-fcgi-omero.conf
    - omero/sysadmins/unix/apache-omero.conf

**Pull request closed without merging**
