### PR TITLE
Adding note re:web deps upgrade

### PR DESCRIPTION
**Pull request by hflynn**
See @jburel 's comment on https://github.com/openmicroscopy/ome-documentation/pull/1417

### CODE REVIEW

**Comment by jburel** [comment]
Thanks for adding the note, 
Better to be on safe side, I will also add a note the release template since we should check that the steps are fully tested/mentioned in announcement

**Comment by hflynn** [comment]
https://www.openmicroscopy.org/site/support/omero5.2-staging/sysadmins/server-upgrade.html#omero-web-dependencies

**Comment by atarkowska** [comment]
@jburel we test daily upgrade. I am guessing we should pick up any breaking changes straight away.

**Comment by hflynn** [comment]
Up to you whether you want to merge this or not @jburel - I certainly don't see the harm

**Comment by jburel** [comment]
As I indicated, it is better to be on the safe side. no harm adding the note in my opinion.
As we have seen with pillow last time (cap to 2.9), we did not catch the problem until we deployed on nightshade even if it is built and deployed daily.

**Comment by atarkowska** [comment]
@jburel I am saying we are testing the latest version of web dependencies on ci, everyday virtualenv is updated with the latest version. if you wish I can add pillow, numpy and more... Then we will pick that up in the future

**Comment by atarkowska** [comment]
My previous comment is not about the note block, just general comment. Note is definitely good idea.

**Comment by jburel** [comment]
@aleksandra-tarkowska: ok I understood your comment was related to the note, we certainly need to discuss the upgrade strategy so we do not miss anything.
Thanks for taking care of it in the first place. 
Merging

**Pull request merged**
